Repository concord-consortium/collaborative-learning, pull requests merged in 2023-12, with the labels that each got.

#2077 Document Flipper Automation
  .github/workflows/manual-regression.yml
  cypress/e2e/functional/teacher_tests/teacher_starreddocument_scroller_spec.js
  cypress/support/elements/common/StarredTab.js
Labels: run regression

#2078 Only render EditableGraphValue if the axis is numeric
  src/plugins/graph/components/graph.tsx
Labels: approved QA review, run regression

#2069 split ui store into UI and persistentUI
  src/clue/components/clue-app-content.tsx
  src/clue/components/teacher/teacher-group-six-pack-fourup.tsx
  src/components/chat/comment-card.tsx
  src/components/chat/commented-documents.tsx
  src/components/document/annotation-layer.tsx
  src/components/document/document-content.tsx
  src/components/document/document-workspace.tsx
  src/components/document/document.tsx
  src/components/document/editable-document-content.tsx
  src/components/document/group-virtual-document.tsx
  src/components/document/student-group-view.tsx
  src/components/four-up.test.tsx
  src/components/four-up.tsx
  src/components/navigation/document-view.tsx
  src/components/navigation/nav-tab-panel.tsx
  src/components/navigation/problem-tab-content.tsx
  src/components/navigation/section-document-or-browser.tsx
  src/components/playback/marker-toolbar.tsx
  src/components/playback/playback-control.tsx
  src/components/playback/playback.tsx
  src/components/thumbnail/class-logs.tsx
  src/components/tiles/tile-component.tsx
  src/components/toolbar.tsx
  src/components/workspace/resize-panel-divider.tsx
  src/components/workspace/workspace.tsx
  src/hooks/use-stores.test.ts
  src/hooks/use-stores.ts
  src/initialize-app.tsx
  src/lib/logger.test.ts
  src/lib/logger.ts
  src/models/stores/base-stores-types.ts
  src/models/stores/persistent-ui.ts
  src/models/stores/stores.test.ts
  src/models/stores/stores.ts
  src/models/stores/ui.test.ts
  src/models/stores/ui.ts
  src/plugins/data-card/data-card-tile.tsx
  src/plugins/dataflow/components/dataflow-tile.tsx
  src/plugins/graph/models/graph-layer-model.ts
Labels: run regression

#2081 Added cypress tests for edit box in xy-plot axes
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
  src/plugins/graph/components/editable-graph-value.tsx
Labels: run regression

#2071 186581572 Import Plotted Function Adorment from Codap
  src/plugins/graph/adornments/adornment-types.ts
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-component.scss
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-component.tsx
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-model.test.ts
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-model.ts
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-registration.test.ts
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-registration.tsx
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-types.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/graph/register-adornment-types.ts
  src/plugins/graph/utilities/graph-utils.ts
Labels: approved QA review, run regression

#2085 186631276 patch typeahead menu so it does not expand card row
  src/plugins/data-card/data-card-tile.scss
Labels: approved QA review, run regression

#2084 186507002 Plot Function from Shared Variables Model
  docs/variables.md
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-component.tsx
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-model.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/graph/utilities/graph-utils.ts
  src/plugins/shared-variables/shared-variables.ts
Labels: approved QA review, run regression

#2086 "View data as graph" button in Diagram
  src/clue/app-config.json
  src/components/tiles/table/table-toolbar-registration.tsx
  src/hooks/use-consumer-tile-linking.ts
  src/hooks/use-link-consumer-tile-dialog.tsx
  src/models/shared/shared-data-utils.ts
  src/plugins/data-card/components/data-card-toolbar-buttons.tsx
  src/plugins/dataflow/components/ui/dataflow-program-link-table-button.tsx
  src/plugins/diagram-viewer/diagram-registration.ts
  src/plugins/diagram-viewer/diagram-tile.tsx
  src/plugins/diagram-viewer/diagram-toolbar-buttons.tsx
  src/plugins/shared-variables/shared-variables-link-button.tsx
Labels: approved QA review, run regression

#2063 XY Plot displays multiple numeric datasets
  src/models/data/data-set.ts
  src/plugins/graph/adornments/adornment.tsx
  src/plugins/graph/adornments/adornments.tsx
  src/plugins/graph/adornments/connecting-lines/connecting-lines.tsx
  src/plugins/graph/components/attribute-label.tsx
  src/plugins/graph/components/background.tsx
  src/plugins/graph/components/casedots.tsx
  src/plugins/graph/components/chartdots.tsx
  src/plugins/graph/components/dotplotdots.tsx
  src/plugins/graph/components/graph-axis.tsx
  src/plugins/graph/components/graph-component.tsx
  src/plugins/graph/components/graph-layer.tsx
  src/plugins/graph/components/graph.tsx
  src/plugins/graph/components/legend/categorical-legend.tsx
  src/plugins/graph/components/legend/layer-legend.tsx
  src/plugins/graph/components/legend/multi-legend.tsx
  src/plugins/graph/components/legend/numeric-legend.tsx
  src/plugins/graph/components/scatterdots.tsx
  src/plugins/graph/components/simple-attribute-label.tsx
  src/plugins/graph/d3-types.ts
  src/plugins/graph/hooks/use-data-tips.ts
  src/plugins/graph/hooks/use-graph-controller.ts
  src/plugins/graph/hooks/use-graph-layer-context.ts
  src/plugins/graph/hooks/use-graph-model-context.ts
  src/plugins/graph/hooks/use-graph-model.ts
  src/plugins/graph/hooks/use-init-graph-layout.ts
  src/plugins/graph/hooks/use-movables.ts
  src/plugins/graph/hooks/use-plot.ts
  src/plugins/graph/hooks/use-point-locations.ts
  src/plugins/graph/imports/components/axis/hooks/use-sub-axis.ts
  src/plugins/graph/imports/hooks/use-drop-hint-string.ts
  src/plugins/graph/models/data-configuration-model.test.ts
  src/plugins/graph/models/data-configuration-model.ts
  src/plugins/graph/models/graph-controller.ts
  src/plugins/graph/models/graph-layer-model.ts
  src/plugins/graph/models/graph-model.test.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/graph/utilities/graph-utils.ts
  src/utilities/math-utils.ts
Labels: approved QA review, run regression

#2090 Graph toolbar "Fit All" button
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  src/clue/app-config.json
  src/plugins/graph/assets/fit-all-icon.svg
  src/plugins/graph/components/graph-component.test.tsx
  src/plugins/graph/components/graph-component.tsx
  src/plugins/graph/components/graph-toolbar-registration.tsx
  src/plugins/graph/components/graph-wrapper-component.tsx
  src/plugins/graph/models/graph-controller.ts
Labels: approved QA review, run regression

#2080 186581030 save and restore persistent UI
  cypress/e2e/functional/document_tests/group_test_spec.js
  cypress/e2e/functional/portal_user_tests/teacher_chat_spec.js
  cypress/e2e/functional/teacher_tests/history_playback_spec.js
  cypress/e2e/functional/teacher_tests/teacher_curation_spec.js
  cypress/e2e/functional/teacher_tests/teacher_dashboard_4_quadrants_spec.js
  cypress/e2e/functional/teacher_tests/teacher_dashboard_spec.js
  cypress/e2e/functional/teacher_tests/teacher_six_pack_spec.js
  cypress/e2e/functional/teacher_tests/teacher_starreddocument_scroller_spec.js
  cypress/e2e/functional/teacher_tests/teacher_workspace_spec.js
  src/components/app.tsx
  src/lib/db-listeners/db-problem-documents-listener.ts
  src/lib/db-types.ts
  src/lib/db.test.ts
  src/lib/db.ts
  src/lib/firebase.ts
  src/models/stores/persistent-ui.ts
  src/utilities/url-params.ts
Labels: approved QA review, run regression

#2098 Geometry & Graph tile renaming
  cypress/e2e/functional/document_tests/canvas_test_spec.js
  cypress/e2e/functional/tile_tests/arrow_annotation_spec.js
  cypress/e2e/functional/tile_tests/geometry_table_integraton_test_spec.js
  cypress/e2e/functional/tile_tests/geometry_tool_spec.js
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  cypress/e2e/smoke/single_student_canvas_test.js
  cypress/support/commands.js
  cypress/support/elements/common/cCanvas.js
  cypress/support/elements/tile/GeometryToolTile.js
  src/clue/assets/icons/geometry-tool.svg
  src/components/tiles/geometry/use-axis-settings-dialog.tsx
  src/models/document/document-content-tests/dc-general.test.ts
  src/models/tiles/geometry/geometry-registration.ts
  src/plugins/graph/graph-registration.ts
Labels: approved QA review, run regression

#2097 Handle tile render errors
  cypress/e2e/functional/tile_tests/tile_error_spec.js
  package-lock.json
  package.json
  src/components/document/canvas.tsx
  src/components/document/document-error.tsx
  src/lib/db-listeners/db-other-docs-listener.ts
  src/lib/db-listeners/db-problem-documents-listener.ts
  src/lib/db.ts
  src/lib/firebase.ts
  src/plugins/error-test/README.md
  src/plugins/error-test/error-test-content.ts
  src/plugins/error-test/error-test-icon.svg
  src/plugins/error-test/error-test-registration.ts
  src/plugins/error-test/error-test-tile.scss
  src/plugins/error-test/error-test-tile.tsx
  src/plugins/error-test/error-test-types.ts
  src/public/curriculum/example-curriculum/error-document.json
  src/public/curriculum/example-curriculum/error-unit.json
  src/register-tile-types.ts
Labels: approved QA review, run regression

#2104 Check if chat toggle is available before clicking it
  cypress/e2e/cleanup/remove_teacher_comment_spec.js
  cypress/support/elements/common/ChatPanel.js
Labels: run regression

#2101 added automation for Duplicate Card in Datacard tile
  cypress/e2e/functional/tile_tests/data_card_tool_spec.js
Labels: run regression

#2103 Added cypress tests for xy-plot axis bounds edit boxes
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
Labels: run regression

#2100 Link button/dialog updates
  cypress/e2e/functional/tile_tests/data_card_tool_spec.js
  cypress/e2e/functional/tile_tests/table_tool_spec.js
  cypress/support/elements/tile/DataCardToolTile.js
  cypress/support/elements/tile/TableToolTile.js
  src/assets/icons/add-data-graph-icon.svg
  src/components/shared/data-set-view-button.tsx
  src/components/tiles/table/table-toolbar-registration.tsx
  src/components/toolbar/data-set-view-button.tsx
  src/hooks/use-link-consumer-tile-dialog.tsx
  src/hooks/use-link-provider-tile-dialog.tsx
  src/hooks/use-provider-tile-linking.tsx
  src/plugins/data-card/components/data-card-toolbar-buttons.tsx
  src/plugins/graph/components/graph-toolbar-registration.tsx
  src/plugins/shared-variables/shared-variables-link-button.tsx
Labels: approved QA review, run regression

#2106 186507040 Multiple Variable Plots
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
  src/plugins/graph/adornments/plotted-function/plotted-variables/plotted-variables-adornment-component.tsx
  src/plugins/graph/components/legend/multi-legend.scss
  src/plugins/graph/components/legend/multi-legend.tsx
  src/plugins/graph/components/legend/variable-function-legend.tsx
  src/plugins/graph/components/legend/variable-selection.tsx
Labels: approved QA review, run regression

#2109 186487775 Graph Colors
  src/plugins/graph/adornments/connecting-lines/connecting-lines.tsx
  src/plugins/graph/components/casedots.tsx
  src/plugins/graph/components/chartdots.tsx
  src/plugins/graph/components/dotplotdots.tsx
  src/plugins/graph/components/legend/layer-legend.tsx
  src/plugins/graph/components/scatterdots.tsx
  src/plugins/graph/components/simple-attribute-label.tsx
  src/plugins/graph/hooks/use-point-locations.ts
  src/plugins/graph/models/graph-model.test.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/graph/utilities/graph-utils.ts
  src/utilities/color-utils.ts
Labels: approved QA review, run regression

#2111 186569351 Make Graph Dropdowns Render Over Tile Toolbar
  src/plugins/graph/components/attribute-label.tsx
  src/plugins/graph/components/legend/variable-selection.tsx
  src/plugins/graph/components/simple-attribute-label.tsx
  src/plugins/graph/graph-types.ts
Labels: pending QA review, run regression

#2118 Tile title changes restore
  cypress/e2e/functional/tile_tests/data_card_tool_spec.js
  cypress/e2e/functional/tile_tests/diagram_tool_spec.js
  cypress/e2e/functional/tile_tests/drawing_tool_spec.js
  cypress/e2e/functional/tile_tests/expression_tool_spec.js
  cypress/e2e/functional/tile_tests/geometry_tool_spec.js
  cypress/e2e/functional/tile_tests/image_tool_spec.js
  cypress/e2e/functional/tile_tests/numberline_tool_spec.js
  cypress/e2e/functional/tile_tests/simulator_tile_spec.js
  cypress/e2e/functional/tile_tests/table_tool_spec.js
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
Labels: run regression
