Repository concord-consortium/collaborative-learning, pull requests merged in 2023-09, with the labels that each got.

#1879 185477199 numberline plot points
  cypress/e2e/clue/branch/student_tests/numberline_tool_spec.js
  cypress/support/elements/clue/NumberlineTile.js
  cypress/support/elements/clue/NumberlineToolTile.js
  cypress/support/elements/clue/cCanvas.js
  src/components/tiles/table/table-toolbar.tsx
  src/plugins/numberline/assets/numberline-toolbar-clear-icon.svg
  src/plugins/numberline/assets/numberline-toolbar-delete-icon.svg
  src/plugins/numberline/assets/numberline-toolbar-point-icon.svg
  src/plugins/numberline/models/numberline-content.test.ts
  src/plugins/numberline/models/numberline-content.ts
  src/plugins/numberline/numberline-content.ts
  src/plugins/numberline/numberline-registration.ts
  src/plugins/numberline/numberline-tile-component.scss
  src/plugins/numberline/numberline-tile-component.tsx
  src/plugins/numberline/numberline-tile-constants.ts
  src/plugins/numberline/numberline-tile.scss
  src/plugins/numberline/numberline-tile.test.tsx
  src/plugins/numberline/numberline-tile.tsx
  src/plugins/numberline/numberline-toolbar-buttons.tsx
  src/plugins/numberline/numberline-toolbar.scss
  src/plugins/numberline/numberline-toolbar.tsx
  src/plugins/numberline/numberline-types.ts
Labels: approved QA review

#1906 Delete and check serialization ticket
  src/plugins/numberline/models/numberline-content.ts
  src/plugins/numberline/numberline-tile-component.tsx
  src/plugins/numberline/numberline-tile.tsx
  src/plugins/numberline/numberline-toolbar-buttons.tsx
  src/plugins/numberline/numberline-toolbar.tsx
Labels: approved QA review

#1902 185647872 connected plot points 2
  src/plugins/graph/adornments/adornment-types.ts
  src/plugins/graph/adornments/adornment.tsx
  src/plugins/graph/adornments/adornments.tsx
  src/plugins/graph/adornments/connecting-lines/connecting-lines-model.test.ts
  src/plugins/graph/adornments/connecting-lines/connecting-lines-model.ts
  src/plugins/graph/adornments/connecting-lines/connecting-lines-registration.ts
  src/plugins/graph/adornments/connecting-lines/connecting-lines-types.ts
  src/plugins/graph/adornments/connecting-lines/connecting-lines.tsx
  src/plugins/graph/components/graph.tsx
  src/plugins/graph/hooks/use-point-locations.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/graph/register-adornment-types.ts
  src/plugins/graph/utilities/graph-utils.ts
Labels: approved QA review

#1911 Animate the collapsing of the right and left panels
  cypress/e2e/clue/branch/student_tests/arrow_annotation_spec.js
  cypress/e2e/clue/branch/student_tests/canvas_test_spec.js
  cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js
  cypress/e2e/clue/branch/student_tests/diagram_tool_spec.js
  cypress/e2e/clue/branch/student_tests/drawing_tool_spec.js
  cypress/e2e/clue/branch/student_tests/image_tool_spec.js
  cypress/e2e/clue/branch/student_tests/nav_panel_test_spec.js
  cypress/e2e/clue/branch/student_tests/table_tool_spec.js
  cypress/e2e/clue/branch/student_tests/workspace_test_spec.js
  cypress/e2e/clue/branch/teacher_tests/teacher_network_spec.js
  cypress/e2e/clue/branch/teacher_tests/teacher_workspace_spec.js
  cypress/e2e/clue/full/teacher_tests/teacher_dashboard_spec.js
  cypress/e2e/clue/smoke/single_student_canvas_test.js
  cypress/support/commands.js
  cypress/support/elements/clue/ResourcesPanel.js
  cypress/support/elements/common/PrimaryWorkspace.js
  src/components/document/canvas.tsx
  src/components/document/collapsed-document-workspace-tab.scss
  src/components/document/collapsed-document-workspace-tab.tsx
  src/components/document/document-workspace.sass
  src/components/navigation/nav-tab-panel.sass
  src/components/workspace/resizable-panel.scss
  src/components/workspace/resizable-panel.tsx
  src/components/workspace/resize-panel-divider.scss
  src/components/workspace/resize-panel-divider.tsx
  src/components/workspace/resources-expander.scss
  src/components/workspace/resources-expander.tsx
  src/components/workspace/workspace-expander.scss
  src/components/workspace/workspace-expander.tsx
  src/components/workspace/workspace.tsx
  src/models/stores/nav-tabs.ts
  src/utilities/hot-keys.ts
Labels: approved QA review

#1897 strip commas from numbers
  src/models/data/attribute.ts
  src/models/data/data-types.test.ts
  src/models/data/data-types.ts
Labels: approved QA review

#1907 185744763 Readonly Sparrows
  src/components/annotations/arrow-annotation.tsx
  src/components/annotations/curved-arrow.tsx
  src/components/chat/commented-documents.tsx
  src/components/document/annotation-layer.tsx
  src/components/document/canvas.tsx
  src/components/document/editable-document-content.tsx
  src/components/four-up.tsx
  src/components/navigation/problem-panel.tsx
  src/components/thumbnail/class-logs.tsx
  src/components/thumbnail/collapsible-document-section.tsx
  src/components/thumbnail/decorated-document-thumbnail-item.tsx
  src/components/thumbnail/documents-type-collection.tsx
  src/components/thumbnail/thumbnail-document-item.tsx
  src/hooks/use-document-caption.tsx
  src/models/annotations/arrow-annotation.ts
  src/models/document/base-document-content.ts
  src/models/document/document-content.ts
Labels: approved QA review

#1908 Group and ungroup objects in drawing tile (PT #185447627 and #185447632)
  cypress/e2e/clue/branch/student_tests/drawing_tool_spec.js
  cypress/support/elements/clue/DrawToolTile.js
  src/plugins/drawing/assets/freehand-icon.svg
  src/plugins/drawing/assets/group-objects-icon.svg
  src/plugins/drawing/assets/ungroup-objects-icon.svg
  src/plugins/drawing/components/__snapshots__/drawing-layer-legacy.test.tsx.snap
  src/plugins/drawing/components/__snapshots__/drawing-layer.test.tsx.snap
  src/plugins/drawing/components/drawing-layer.tsx
  src/plugins/drawing/components/drawing-object-manager.tsx
  src/plugins/drawing/components/drawing-tile.scss
  src/plugins/drawing/components/drawing-toolbar-buttons.tsx
  src/plugins/drawing/components/drawing-toolbar.tsx
  src/plugins/drawing/model/drawing-basic-types.ts
  src/plugins/drawing/model/drawing-content.test.ts
  src/plugins/drawing/model/drawing-content.ts
  src/plugins/drawing/objects/drawing-object.ts
  src/plugins/drawing/objects/ellipse.tsx
  src/plugins/drawing/objects/group.tsx
  src/plugins/drawing/objects/image.tsx
  src/plugins/drawing/objects/line.tsx
  src/plugins/drawing/objects/rectangle.tsx
  src/plugins/drawing/objects/text.tsx
  src/plugins/drawing/objects/vector.tsx
Labels: approved QA review

#1909 Sparrow design update
  src/clue/assets/icons/hide-annotations-tool.svg
  src/clue/assets/icons/show-annotations-tool.svg
  src/clue/assets/icons/sparrow-tool.svg
  src/components/annotations/annotation-utilities.ts
  src/components/annotations/arrow-annotation.scss
  src/components/annotations/arrow-annotation.tsx
  src/components/annotations/preview-arrow.tsx
  src/components/document/annotation-layer.tsx
  src/components/toolbar.sass
  src/components/toolbar.scss
  src/components/toolbar.tsx
  src/components/vars.sass
  src/models/annotations/arrow-annotation.ts
  src/models/stores/ui.ts
Labels: approved QA review

#1915 fix document scroller by refactoring css and code
  src/components/navigation/document-browser-scroller.scss
  src/components/navigation/document-browser-scroller.tsx
  src/components/navigation/document-view.tsx
  src/components/navigation/section-document-or-browser.scss
Labels: approved QA review

#1916 185538971 Geometry Sparrows
  cypress/e2e/clue/branch/student_tests/arrow_annotation_spec.js
  cypress/e2e/clue/branch/student_tests/graph_tool_spec.js
  src/components/annotations/annotation-button.scss
  src/components/annotations/annotation-button.tsx
  src/components/annotations/annotation-utilities.ts
  src/components/document/annotation-layer.tsx
  src/components/tiles/geometry/geometry-constants.ts
  src/components/tiles/geometry/geometry-content.tsx
  src/components/tiles/tile-api.tsx
  src/models/tiles/geometry/geometry-content.ts
  src/models/tiles/geometry/geometry-model.ts
  src/utilities/math-utils.ts
Labels: approved QA review

#1918 fix image being identified as date
  src/models/data/attribute.test.ts
  src/models/data/data-types.test.ts
  src/models/data/data-types.ts
Labels: approved QA review

#1910 Drawing object list/order/visibility panel (#185447641)
  cypress/e2e/clue/branch/student_tests/drawing_tool_spec.js
  cypress/support/elements/clue/DrawToolTile.js
  src/plugins/drawing/assets/expand-left-icon.svg
  src/plugins/drawing/assets/expand-right-icon.svg
  src/plugins/drawing/assets/hide-object-icon.svg
  src/plugins/drawing/assets/move-icon.svg
  src/plugins/drawing/assets/show-object-icon.svg
  src/plugins/drawing/components/drawing-layer.tsx
  src/plugins/drawing/components/drawing-tile.scss
  src/plugins/drawing/components/drawing-tile.tsx
  src/plugins/drawing/components/object-list-view.tsx
  src/plugins/drawing/model/drawing-content.ts
  src/plugins/drawing/objects/drawing-object.ts
  src/plugins/drawing/objects/ellipse.tsx
  src/plugins/drawing/objects/group.tsx
  src/plugins/drawing/objects/image.tsx
  src/plugins/drawing/objects/line.tsx
  src/plugins/drawing/objects/rectangle.tsx
  src/plugins/drawing/objects/text.tsx
  src/plugins/drawing/objects/vector.tsx
Labels: approved QA review

#1914 Show thumbnails of images in table tile (PT #185780804)
  cypress/e2e/clue/branch/student_tests/graph_table_integraton_test_spec.js
  src/components/tiles/table/cell-formatter.scss
  src/components/tiles/table/cell-formatter.tsx
  src/components/tiles/table/table-tile.tsx
  src/components/tiles/table/table-types.ts
  src/components/tiles/table/use-columns-from-data-set.ts
  src/components/tiles/table/use-data-set.ts
  src/components/tiles/table/use-row-height.ts
Labels: approved QA review

#1912 185817277 resize data card
  src/plugins/data-card/data-card-tile.test.tsx
  src/plugins/data-card/data-card-tile.tsx
  src/plugins/data-card/data-card-types.ts
  src/plugins/data-card/use-data-card-tile-height.ts
Labels: approved QA review

#1919 185744824 Authoring Sparrows
  cypress/e2e/clue/branch/student_tests/arrow_annotation_spec.js
  cypress/support/elements/clue/cCanvas.js
  src/components/navigation/problem-panel.sass
  src/components/navigation/problem-panel.scss
  src/components/navigation/problem-panel.tsx
  src/models/annotations/arrow-annotation.ts
  src/models/annotations/clue-object.ts
  src/models/document/base-document-content.ts
  src/models/document/document-content-import-types.ts
  src/models/document/document-content-import.ts
  src/models/document/document-content-types.ts
  src/models/document/document-content-with-annotations.ts
  src/models/document/document-content.ts
  src/models/document/drag-tiles.test.ts
  src/models/document/drag-tiles.ts
  src/models/tiles/table/table-content.ts
  src/models/tiles/table/table-registration.ts
  src/models/tiles/table/table-utils.ts
  src/models/tiles/tile-content-info.ts
Labels: approved QA review

#1929 Preprocess to remove stray null values in drawing
  src/plugins/drawing/objects/line.tsx
Labels: approved QA review

#1922 185798493 Fix Publishing Sparrows with Deleted Tiles
  src/models/annotations/arrow-annotation.ts
Labels: approved QA review

#1923 Group and ungroup keyboard shortcuts (PT-185994631)
  src/plugins/drawing/components/drawing-tile.tsx
  src/plugins/drawing/objects/group.tsx
Labels: approved QA review

#1930 186002744 avoid drawing nulls 4.6.x
  src/plugins/drawing/objects/line.tsx
Labels: approved QA review

#1920 185477232 Numberline Sparrows
  cypress/e2e/clue/branch/student_tests/arrow_annotation_spec.js
  cypress/support/elements/clue/NumberlineToolTile.js
  src/components/tiles/basic-editable-tile-title.tsx
  src/plugins/numberline/components/numberline-tile.scss
  src/plugins/numberline/components/numberline-tile.tsx
  src/plugins/numberline/components/numberline-toolbar-buttons.tsx
  src/plugins/numberline/components/numberline-toolbar.scss
  src/plugins/numberline/components/numberline-toolbar.tsx
  src/plugins/numberline/models/numberline-content.ts
  src/plugins/numberline/numberline-registration.ts
  src/plugins/numberline/numberline-tile-component.scss
  src/plugins/numberline/numberline-tile-component.tsx
  src/plugins/numberline/numberline-tile-constants.ts
  src/plugins/numberline/numberline-tile.tsx
Labels: approved QA review

#1927 185995133 Sparrow Rerenders
  src/components/document/annotation-layer.tsx
  src/components/document/canvas.tsx
  src/components/tiles/geometry/geometry-content.tsx
  src/components/tiles/placeholder/placeholder-tile.sass
  src/components/tiles/placeholder/placeholder-tile.scss
  src/components/tiles/placeholder/placeholder-tile.tsx
  src/components/tiles/section-header.sass
  src/components/tiles/section-header.scss
  src/components/tiles/section-header.tsx
  src/components/tiles/table/table-tile.tsx
  src/components/tiles/table/use-columns-from-data-set.ts
  src/components/tiles/table/use-content-change-handlers.ts
  src/components/tiles/table/use-controls-column.tsx
  src/components/tiles/table/use-measure-column-width.ts
  src/hooks/use-did-change.ts
  src/hooks/use-tooltip-options.ts
  src/models/annotations/arrow-annotation.ts
  src/models/document/base-document-content.ts
  src/models/document/document-constants.ts
  src/models/tiles/placeholder/placeholder-constants.ts
  src/models/tiles/placeholder/placeholder-registration.ts
Labels: pending QA review

#1921 185782082 data deck attribute value drop down and type-ahead
  cypress/e2e/clue/branch/student_tests/data_card_tool_spec.js
  cypress/support/elements/clue/DataCardToolTile.js
  package-lock.json
  package.json
  src/plugins/data-card/components/case-attribute.tsx
  src/plugins/data-card/data-card-tile.scss
Labels: approved QA review

#1931 Draw tool object ordering using show/sort panel (PT-185447638)
  package-lock.json
  package.json
  src/plugins/drawing/components/drawing-layer.tsx
  src/plugins/drawing/components/drawing-tile.scss
  src/plugins/drawing/components/drawing-tile.test.tsx
  src/plugins/drawing/components/object-list-view.tsx
  src/plugins/drawing/model/drawing-basic-types.ts
  src/plugins/drawing/model/drawing-content.test.ts
  src/plugins/drawing/model/drawing-content.ts
  src/plugins/drawing/objects/vector.tsx
  src/plugins/shared-variables/drawing/variable-object.tsx
Labels: approved QA review

#1933 PT-186033421 Fix 'Cannot access g' bug
  docs/dependency-cruiser.md
  src/plugins/drawing/components/drawing-object-manager.tsx
  src/plugins/drawing/components/drawing-toolbar-buttons.tsx
  src/plugins/drawing/components/drawing-toolbar-group-buttons.tsx
  src/plugins/drawing/drawing-registration.ts
  src/plugins/drawing/model/drawing-content.test.ts
  src/plugins/drawing/objects/group.tsx
Labels: approved QA review

#1935 186033421 cannot access g v4.6.x
  docs/dependency-cruiser.md
  src/plugins/drawing/components/drawing-object-manager.tsx
  src/plugins/drawing/components/drawing-toolbar-buttons.tsx
  src/plugins/drawing/components/drawing-toolbar-group-buttons.tsx
  src/plugins/drawing/drawing-registration.ts
  src/plugins/drawing/model/drawing-content.test.ts
  src/plugins/drawing/objects/group.tsx
Labels: approved QA review

#1924 treat fractions as numeric values
  src/models/data/attribute.test.ts
  src/models/data/data-types.test.ts
  src/models/data/data-types.ts
Labels: approved QA review

#1937 Add visibility toggle to drawing show/sort panel (PT-185787939)
  cypress/e2e/clue/branch/student_tests/drawing_tool_spec.js
  cypress/support/elements/clue/DrawToolTile.js
  src/plugins/drawing/components/__snapshots__/drawing-layer.test.tsx.snap
  src/plugins/drawing/components/drawing-layer.test.tsx
  src/plugins/drawing/components/drawing-layer.tsx
  src/plugins/drawing/components/drawing-object-manager.tsx
  src/plugins/drawing/components/drawing-tile.scss
  src/plugins/drawing/components/object-list-view.tsx
  src/plugins/drawing/model/drawing-change-playback.test.ts
  src/plugins/drawing/model/drawing-content.test.ts
  src/plugins/drawing/model/drawing-content.ts
  src/plugins/drawing/model/drawing-export.test.ts
  src/plugins/drawing/model/drawing-import.test.ts
  src/plugins/drawing/objects/drawing-object.tsx
  src/plugins/drawing/objects/ellipse.tsx
  src/plugins/drawing/objects/group.tsx
  src/plugins/drawing/objects/image.tsx
  src/plugins/drawing/objects/line.tsx
  src/plugins/drawing/objects/rectangle.tsx
  src/plugins/drawing/objects/text.tsx
  src/plugins/drawing/objects/vector.tsx
  src/plugins/shared-variables/drawing/variable-object.tsx
Labels: approved QA review

#1936 185788995 deck merge 3
  cypress/e2e/clue/branch/student_tests/datacard_merge_spec.js
  cypress/support/elements/clue/DataCardToolTile.js
  src/hooks/link-tile-dialog.scss
  src/hooks/use-merge-data-dialog.tsx
  src/hooks/use-tile-data-merging.ts
  src/models/shared/shared-data-utils.ts
  src/models/tiles/tile-link-types.ts
  src/plugins/data-card/assets/merge-in-icon.svg
  src/plugins/data-card/components/data-card-toolbar-buttons.tsx
  src/plugins/data-card/data-card-tile.tsx
  src/plugins/data-card/data-card-toolbar.scss
  src/plugins/data-card/data-card-toolbar.tsx
Labels: approved QA review

#1942 DataCard dropdown shows all values initially, then filters
  src/plugins/data-card/components/case-attribute.tsx
Labels: pending QA review

#1945 Update Add Data icon
  src/hooks/link-tile-dialog.scss
  src/plugins/data-card/assets/merge-in-icon.svg
  src/plugins/data-card/data-card-toolbar.scss
Labels: approved QA review

#1944 185952384 claw sim jump bug
  src/plugins/dataflow/nodes/factories/live-output-rete-node-factory.tsx
  src/plugins/dataflow/nodes/utilities/update-utilities.ts
Labels: approved QA review

#1939 generic button for viewing datasets in other tiles
  src/assets/icons/view/view-badge.svg
  src/components/document/canvas.tsx
  src/components/shared/data-set-view-button.scss
  src/components/shared/data-set-view-button.tsx
  src/components/shared/tile-toolbar-button.tsx
  src/components/tiles/table/table-toolbar.tsx
  src/components/tiles/tile-api.tsx
  src/components/tiles/tile-component.tsx
  src/models/document/base-document-content.ts
  src/models/document/document-content.ts
  src/models/document/shared-model-document-manager.test.ts
  src/models/mst.test.ts
  src/plugins/data-card/data-card-content.ts
  src/plugins/data-card/data-card-tile.tsx
  src/plugins/data-card/data-card-toolbar.tsx
  src/public/curriculum/example-curriculum/example-curriculum.json
Labels: approved QA review

#1952 adjust hardware output configuration for new version of gripper
  src/models/stores/serial.ts
  src/plugins/dataflow/model/utilities/node.ts
Labels: approved QA review

#1953 185631830 Terrarium Simulation Variable Icons
  src/plugins/dataflow/model/utilities/node.ts
  src/plugins/shared-assets/icons/dataflow/output/fan.svg
  src/plugins/shared-assets/icons/dataflow/output/humid.svg
  src/plugins/shared-assets/icons/dataflow/output/light-bulb.svg
  src/plugins/shared-assets/icons/dataflow/sensor/humidity.svg
  src/plugins/shared-assets/icons/dataflow/sensor/temperature.svg
  src/plugins/shared-assets/icons/icon-utilities.tsx
Labels: approved QA review

#1954 186036945 Fix Deleted Geometry Polygons with Sparrows
  src/components/tiles/geometry/geometry-content.tsx
Labels: approved QA review

#1938 185816591 xy plot sparrows
  cypress/e2e/clue/branch/student_tests/arrow_annotation_spec.js
  cypress/support/elements/clue/XYPlotToolTile.js
  docs/annotations.md
  src/components/annotations/annotation-button.scss
  src/components/annotations/annotation-button.tsx
  src/components/annotations/annotation-node.tsx
  src/components/annotations/annotation-utilities.ts
  src/components/annotations/arrow-annotation.tsx
  src/components/annotations/preview-arrow.tsx
  src/components/document/annotation-layer.tsx
  src/components/tiles/geometry/geometry-constants.ts
  src/components/tiles/geometry/geometry-content.tsx
  src/components/tiles/table/use-tile-api.ts
  src/components/tiles/tile-api.tsx
  src/plugins/graph/components/graph-component.test.tsx
  src/plugins/graph/components/graph-component.tsx
  src/plugins/graph/components/graph-wrapper-component.tsx
  src/plugins/graph/components/graph.tsx
  src/plugins/graph/graph-registration.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/graph/utilities/graph-utils.ts
  src/plugins/numberline/components/numberline-tile.tsx
  src/plugins/numberline/numberline-tile-constants.ts
Labels: approved QA review

#1959 186036945 deleted geometry sparrows 4.7.x
  src/components/tiles/geometry/geometry-content.tsx
Labels: run regression

#1962 clean up link index, color code
  src/components/tiles/geometry/geometry-content.tsx
  src/components/tiles/geometry/geometry-tile.tsx
  src/components/tiles/table/editable-table-title.tsx
  src/components/tiles/table/link-tile-button.tsx
  src/components/tiles/table/table-tile.tsx
  src/components/tiles/table/table-toolbar-buttons.tsx
  src/components/tiles/table/table-toolbar.tsx
  src/components/tiles/table/use-tile-api.ts
  src/components/tiles/tile-api.tsx
  src/hooks/use-consumer-tile-linking.ts
  src/hooks/use-provider-tile-linking.tsx
  src/models/tiles/table-links.ts
  src/plugins/data-card/components/data-card-toolbar-buttons.tsx
  src/plugins/data-card/data-card-tile.tsx
  src/plugins/data-card/data-card-toolbar.tsx
  src/plugins/dataflow/components/ui/dataflow-program-link-table-button.tsx
  src/plugins/graph/components/graph-wrapper-component.tsx
  tiles.md
Labels: run regression

#1963 print the urls of the files that fail to load
  src/models/curriculum/unit.ts
Labels: run regression

#1961 186082591 live temperature readings
  cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js
  src/models/stores/serial.ts
  src/plugins/dataflow-tool/arduino/ccemgfsr/ccemgfsr.ino
  src/plugins/dataflow/components/dataflow-program.tsx
  src/plugins/dataflow/model/utilities/channel.ts
Labels: approved QA review

#1960 Fix drawtool cmd-click behavior (PT-185911902)
  cypress/support/elements/clue/DrawToolTile.js
  src/plugins/drawing/components/drawing-layer.tsx
  src/plugins/drawing/components/drawing-tile.tsx
  src/plugins/drawing/components/object-list-view.tsx
  src/plugins/drawing/components/selection-drawing-tool.tsx
  src/plugins/drawing/drawing-registration.ts
  src/plugins/drawing/objects/drawing-object.tsx
  src/plugins/drawing/objects/ellipse.tsx
  src/plugins/drawing/objects/image.tsx
  src/plugins/drawing/objects/line.tsx
  src/plugins/drawing/objects/rectangle.tsx
  src/plugins/drawing/objects/text.tsx
  src/plugins/drawing/objects/vector.tsx
Labels: approved QA review, run regression

#1964 Remove getTitle from component tile api
  src/components/chat/chat-comment-thread.ts
  src/components/document/document-content.tsx
  src/components/tiles/basic-editable-tile-title.tsx
  src/components/tiles/editable-tile-title.tsx
  src/components/tiles/geometry/geometry-content.tsx
  src/components/tiles/image/image-tile.tsx
  src/components/tiles/table/editable-table-title.tsx
  src/components/tiles/table/table-tile.tsx
  src/components/tiles/table/use-table-title.ts
  src/components/tiles/table/use-tile-api.ts
  src/components/tiles/tile-api.tsx
  src/components/tiles/tile-component.tsx
  src/components/toolbar.tsx
  src/hooks/use-link-consumer-tile-dialog.tsx
  src/hooks/use-link-provider-tile-dialog.tsx
  src/hooks/use-merge-data-dialog.tsx
  src/lib/logger-utils.ts
  src/models/document/base-document-content.ts
  src/models/document/document-content-tests/dc-tile-move-copy.test.ts
  src/models/document/document.ts
  src/models/tiles/geometry/geometry-content.ts
  src/models/tiles/image/image-content.ts
  src/models/tiles/table/table-content.ts
  src/models/tiles/tile-content.ts
  src/models/tiles/tile-model-hooks.ts
  src/models/tiles/tile-model.ts
  src/plugins/data-card/data-card-content.ts
  src/plugins/data-card/data-card-tile.tsx
  src/plugins/dataflow/components/dataflow-tile.tsx
  src/plugins/dataflow/dataflow-logger.ts
  src/plugins/dataflow/model/dataflow-content.ts
  src/plugins/diagram-viewer/diagram-tile.tsx
  src/plugins/drawing/components/drawing-tile.test.tsx
  src/plugins/drawing/components/drawing-tile.tsx
  src/plugins/drawing/model/drawing-content.ts
  src/plugins/graph/components/graph-component-title-bar.tsx
  src/plugins/graph/components/graph-wrapper-component.tsx
  src/plugins/graph/imports/components/component-title-bar.tsx
  src/plugins/graph/models/graph-model.ts
  src/plugins/numberline/components/numberline-tile.tsx
  src/plugins/simulator/components/simulator-tile.tsx
  tiles.md
Labels: approved QA review, run regression

#1955 Create common system for tile toolbars (PT-185447570)
  cypress/support/elements/clue/TextToolTile.js
  package-lock.json
  package.json
  src/clue/clue.sass
  src/components/tiles/text/spec-text-tile.tsx
  src/components/tiles/text/text-tile.test.tsx
  src/components/tiles/text/text-tile.tsx
  src/components/tiles/text/toolbar/link-button.tsx
  src/components/tiles/text/toolbar/text-toolbar-registration.tsx
  src/components/tiles/text/toolbar/text-toolbar.tsx
  src/components/tiles/tile-component.scss
  src/components/toolbar/tile-toolbar-button.tsx
  src/components/toolbar/tile-toolbar.test.tsx
  src/components/toolbar/tile-toolbar.tsx
  src/components/toolbar/toolbar-button-manager.tsx
  src/components/toolbar/toolbar.scss
  src/components/toolbar/use-tile-toolbar-positioning.tsx
  src/models/tiles/text/text-plugin-info.ts
  src/plugins/shared-variables/shared-variables-registration.ts
  src/plugins/shared-variables/slate/text-tile-buttons.tsx
Labels: approved QA review, run regression

#1956 fix: tables were not displaying reloaded formulas
  cypress/e2e/clue/branch/student_tests/table_tool_spec.js
  src/components/tiles/table/cell-formatter.tsx
  src/models/tiles/table/table-content.test.ts
  src/models/tiles/table/table-content.ts
Labels: approved QA review, run regression
