Repository concord-consortium/collaborative-learning, pull requests merged in 2023-10, with the labels that each got.

#1957 185952294 Gripper Simulation Temperature Variant
  cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js
  cypress/e2e/clue/branch/student_tests/simulator_tile_spec.js
  cypress/support/elements/clue/SimulatorTile.js
  src/plugins/dataflow/model/utilities/virtual-channel.ts
  src/plugins/simulator/components/simulator-tile.scss
  src/plugins/simulator/components/simulator-tile.tsx
  src/plugins/simulator/components/simulator-variable.scss
  src/plugins/simulator/components/simulator-variable.tsx
  src/plugins/simulator/components/ui/selection-button.scss
  src/plugins/simulator/components/ui/selection-button.tsx
  src/plugins/simulator/model/simulator-content.ts
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/gripper/claw_forPan_00000.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/gripper/claw_forPan_00001.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/gripper/claw_forPan_00002.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/gripper/claw_forPan_00003.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/gripper/claw_forPan_00004.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/gripper/claw_forPan_00005.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/gripper/claw_forPan_00006.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/gripper/claw_forPan_00007.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/gripper/claw_forPan_00008.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/gripper/claw_forPan_00009.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/gripper/claw_forPan_00010.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/pan/pan_frames_00000.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/pan/pan_frames_00001.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/pan/pan_frames_00002.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/pan/pan_frames_00003.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/pan/pan_frames_00004.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/pan/pan_frames_00005.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/pan/pan_frames_00006.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/pan/pan_frames_00007.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/pan/pan_frames_00008.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/pan/pan_frames_00009.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/pan/pan_frames_00010.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00000.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00001.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00002.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00003.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00004.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00005.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00006.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00007.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00008.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00009.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00010.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00011.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00012.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00013.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00014.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00015.png
  src/plugins/simulator/simulations/brainwaves-gripper/assets/temperature/steam/steam_frames_00016.png
  src/plugins/simulator/simulations/brainwaves-gripper/brainwaves-gripper-assets.tsx
  src/plugins/simulator/simulations/brainwaves-gripper/brainwaves-gripper.scss
  src/plugins/simulator/simulations/brainwaves-gripper/brainwaves-gripper.tsx
  src/plugins/simulator/simulations/simulation-types.tsx
Labels: approved QA review, run regression

#1970 handle fractions in table formulas
  cypress/e2e/clue/branch/student_tests/table_tool_spec.js
  src/components/tiles/table/cell-formatter.tsx
  src/models/data/data-types.test.ts
  src/models/tiles/table/table-content.test.ts
  src/models/tiles/table/table-content.ts
Labels: pending QA review, run regression

#1968 use a registration pattern for table toolbar
  cypress/e2e/clue/branch/student_tests/simulator_tile_spec.js
  docs/document-scope.md
  src/components/document/document-content.tsx
  src/components/document/tile-row.tsx
  src/components/shared/data-set-view-button.tsx
  src/components/tiles/basic-editable-tile-title.tsx
  src/components/tiles/geometry/geometry-content.tsx
  src/components/tiles/geometry/geometry-tile.tsx
  src/components/tiles/table/table-tile.tsx
  src/components/tiles/table/table-toolbar-buttons.tsx
  src/components/tiles/table/table-toolbar-context.ts
  src/components/tiles/table/table-toolbar.tsx
  src/components/tiles/table/use-data-set.ts
  src/components/tiles/text/spec-text-tile.tsx
  src/components/tiles/tile-component.test.tsx
  src/components/tiles/tile-component.tsx
  src/components/tiles/tile-title-area.tsx
  src/hooks/use-consumer-tile-linking.ts
  src/hooks/use-linkable-tiles.ts
  src/hooks/use-provider-tile-linking.tsx
  src/models/document/base-document-content.ts
  src/plugins/data-card/data-card-tile.test.tsx
  src/plugins/data-card/data-card-tile.tsx
  src/plugins/dataflow/components/dataflow-tile.tsx
  src/plugins/dataflow/components/ui/dataflow-program-link-table-button.tsx
  src/plugins/drawing/components/drawing-tile.test.tsx
  src/plugins/expression/expression-tile.test.tsx
  src/plugins/graph/components/graph-toolbar.tsx
  src/plugins/graph/components/graph-wrapper-component.tsx
  src/plugins/starter/starter-tile.test.tsx
  tiles.md
Labels: approved QA review, run regression

#1974 these tests are failing locally and on GitHub
  cypress/e2e/clue/full/teacher_tests/teacher_chat_spec.js
  cypress/e2e/clue/full/teacher_tests/teacher_network_problem_chat_spec.js
  cypress/support/elements/clue/ChatPanel.js
Labels: run regression

#1975 186127550 load categorical moth
  src/clue/app-config.json
  src/plugins/graph/models/graph-model.ts
Labels: pending QA review

#1972 support relative unit urls
  README.md
  src/components/doc-editor-app.tsx
  src/lib/auth.ts
  src/models/stores/app-config-model.test.ts
  src/models/stores/app-config-model.ts
  src/utilities/url-utils.test.ts
  src/utilities/url-utils.ts
  webpack.config.js
Labels: run regression

#1971 185952389 Dataflow Labels
  cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js
  cypress/e2e/clue/branch/student_tests/simulator_tile_spec.js
  src/plugins/dataflow/components/ui/dataflow-program-toolbar.tsx
  src/plugins/dataflow/model/utilities/channel.ts
  src/plugins/dataflow/model/utilities/node.ts
  src/plugins/dataflow/model/utilities/virtual-channel.ts
Labels: approved QA review, run regression

#1984 assign random unique ids to tiles without them
  src/models/document/base-document-content.ts
  src/models/document/document-content-tests/dc-general.test.ts
Labels: pending QA review, run regression

#1983 fix: dots should disappear when graph is unlinked
  src/plugins/graph/models/graph-controller.ts
Labels: run regression

#1985 Multiple CI Improvements
  .github/workflows/ci-regression.yml
  .github/workflows/ci.yml
  .github/workflows/regression-daily.yml
  .github/workflows/regression-label.yml
Labels: run regression

#1967 186100096 Fix problems with multiple dataflow and simulation tiles
  src/models/document/document-types.ts
  src/plugins/dataflow/components/dataflow-program.tsx
  src/plugins/dataflow/components/dataflow-tile.tsx
  src/plugins/dataflow/nodes/controls/dropdown-list-control.tsx
  src/plugins/dataflow/nodes/utilities/update-utilities.ts
  src/plugins/simulator/components/simulator-tile.tsx
  src/plugins/simulator/model/simulator-content.ts
  src/plugins/simulator/simulations/simulation-types.tsx
Labels: approved QA review, run regression

#1990 adjust cy tests - we no longer have simulated data streams in the menu
  cypress/e2e/clue/branch/student_tests/simulator_tile_spec.js
Labels: run regression

#1973 use doc-editor.html for the dataflow cypress test
  .github/workflows/ci.yml
  cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js
  cypress/support/elements/common/Canvas.js
  src/clue/components/clue-app-content.tsx
  src/components/doc-editor-app.tsx
  src/components/shared/merge-in-button.tsx
  src/components/shared/tile-toolbar-button.tsx
  src/components/utilities/dialog.tsx
  src/doc-editor.tsx
  src/hooks/use-tile-data-merging.ts
  src/models/mst.test.ts
  src/models/stores/ui.ts
  src/utilities/event-utils.ts
  src/utilities/url-utils.test.ts
Labels: run regression

#1993 186208247-revert-id-change
  src/models/document/base-document-content.ts
  src/models/document/document-content-tests/dc-general.test.ts
Labels: run regression

#1987 185466012 Allow Units to Specify a Default Simulation
  src/clue/app-config.json
  src/plugins/simulator/model/simulator-content.ts
  src/plugins/simulator/simulations/simulations.ts
Labels: approved QA review, run regression

#1998 prevent MST from validating ids in sections
  src/models/curriculum/problem.test.ts
  src/models/curriculum/problem.ts
  src/models/curriculum/section.ts
  src/models/mst.test.ts
Labels: approved QA review, run regression

#1991 Data Card: View Data as Graph (#185968225)
  cypress/e2e/clue/branch/student_tests/data_card_tool_spec.js
  cypress/support/elements/clue/DataCardToolTile.js
  cypress/support/elements/clue/XYPlotToolTile.js
  src/assets/icons/view-data-as-graph-icon.svg
  src/hooks/use-consumer-tile-linking.ts
  src/hooks/use-custom-modal.tsx
  src/hooks/use-link-consumer-tile-dialog.tsx
  src/models/document/document.test.ts
  src/plugins/data-card/components/data-card-toolbar-buttons.tsx
  src/plugins/data-card/data-card-toolbar.tsx
Labels: approved QA review, run regression

#1986 fix: string values should not be plotted on numeric plots
  src/plugins/graph/models/graph-controller.ts
Labels: approved QA review, run regression

#2000 Align icons in drawing tile Show/sort panel
  src/plugins/drawing/components/drawing-tile.scss
Labels: approved QA review, run regression

#1965 185466012 Terrarium Sim Animation
  src/plugins/simulator/simulations/terrarium/assets/condensation_frames/condensation_frames_00000.png
  src/plugins/simulator/simulations/terrarium/assets/condensation_frames/condensation_frames_00001.png
  src/plugins/simulator/simulations/terrarium/assets/condensation_frames/condensation_frames_00002.png
  src/plugins/simulator/simulations/terrarium/assets/condensation_frames/condensation_frames_00003.png
  src/plugins/simulator/simulations/terrarium/assets/condensation_frames/condensation_frames_00004.png
  src/plugins/simulator/simulations/terrarium/assets/condensation_frames/condensation_frames_00005.png
  src/plugins/simulator/simulations/terrarium/assets/condensation_frames/condensation_frames_00006.png
  src/plugins/simulator/simulations/terrarium/assets/condensation_frames/condensation_frames_00007.png
  src/plugins/simulator/simulations/terrarium/assets/condensation_frames/condensation_frames_00008.png
  src/plugins/simulator/simulations/terrarium/assets/condensation_frames/condensation_frames_00009.png
  src/plugins/simulator/simulations/terrarium/assets/condensation_frames/condensation_frames_00010.png
  src/plugins/simulator/simulations/terrarium/assets/condensation_frames/condensation_frames_00011.png
  src/plugins/simulator/simulations/terrarium/assets/display/display.png
  src/plugins/simulator/simulations/terrarium/assets/fan_frames/fan_00000.png
  src/plugins/simulator/simulations/terrarium/assets/fan_frames/fan_00001.png
  src/plugins/simulator/simulations/terrarium/assets/gecko_frames/gecko_frames_00000.png
  src/plugins/simulator/simulations/terrarium/assets/gecko_frames/gecko_frames_00001.png
  src/plugins/simulator/simulations/terrarium/assets/gecko_frames/gecko_frames_00002.png
  src/plugins/simulator/simulations/terrarium/assets/gecko_frames/gecko_frames_00003.png
  src/plugins/simulator/simulations/terrarium/assets/gecko_frames/gecko_frames_00004.png
  src/plugins/simulator/simulations/terrarium/assets/gecko_frames/gecko_frames_00005.png
  src/plugins/simulator/simulations/terrarium/assets/gecko_frames/gecko_frames_00006.png
  src/plugins/simulator/simulations/terrarium/assets/gecko_frames/gecko_frames_00007.png
  src/plugins/simulator/simulations/terrarium/assets/gecko_frames/gecko_frames_00008.png
  src/plugins/simulator/simulations/terrarium/assets/gecko_frames/gecko_frames_00009.png
  src/plugins/simulator/simulations/terrarium/assets/gecko_frames/gecko_frames_00010.png
  src/plugins/simulator/simulations/terrarium/assets/gecko_frames/gecko_frames_00011.png
  src/plugins/simulator/simulations/terrarium/assets/humidifier_frames/humidifier_00000.png
  src/plugins/simulator/simulations/terrarium/assets/humidifier_frames/humidifier_00001.png
  src/plugins/simulator/simulations/terrarium/assets/humidifier_frames/humidifier_00002.png
  src/plugins/simulator/simulations/terrarium/assets/humidifier_frames/humidifier_00003.png
  src/plugins/simulator/simulations/terrarium/assets/humidifier_frames/humidifier_00004.png
  src/plugins/simulator/simulations/terrarium/assets/humidifier_frames/humidifier_00005.png
  src/plugins/simulator/simulations/terrarium/assets/humidifier_frames/humidifier_00006.png
  src/plugins/simulator/simulations/terrarium/assets/humidifier_frames/humidifier_00007.png
  src/plugins/simulator/simulations/terrarium/assets/jar_foreground/jar_foreground.png
  src/plugins/simulator/simulations/terrarium/assets/jar_frames/jar_frames_00000.png
  src/plugins/simulator/simulations/terrarium/assets/jar_frames/jar_frames_00001.png
  src/plugins/simulator/simulations/terrarium/assets/jar_frames/jar_frames_00002.png
  src/plugins/simulator/simulations/terrarium/assets/jar_frames/jar_frames_00003.png
  src/plugins/simulator/simulations/terrarium/assets/jar_frames/jar_frames_00004.png
  src/plugins/simulator/simulations/terrarium/assets/jar_frames/jar_frames_00005.png
  src/plugins/simulator/simulations/terrarium/assets/jar_frames/jar_frames_00006.png
  src/plugins/simulator/simulations/terrarium/assets/jar_frames/jar_frames_00007.png
  src/plugins/simulator/simulations/terrarium/assets/jar_frames/jar_frames_00008.png
  src/plugins/simulator/simulations/terrarium/assets/jar_frames/jar_frames_00009.png
  src/plugins/simulator/simulations/terrarium/assets/jar_frames/jar_frames_00010.png
  src/plugins/simulator/simulations/terrarium/assets/jar_frames/jar_frames_00011.png
  src/plugins/simulator/simulations/terrarium/assets/lamp_frames/lamp_00000.png
  src/plugins/simulator/simulations/terrarium/assets/lamp_frames/lamp_00001.png
  src/plugins/simulator/simulations/terrarium/terrarium-assets.tsx
  src/plugins/simulator/simulations/terrarium/terrarium.scss
  src/plugins/simulator/simulations/terrarium/terrarium.tsx
Labels: pending QA review, run regression

#1989 186164890 Simulation Input Unit Variables
  cypress/e2e/clue/branch/student_tests/simulator_tile_spec.js
  src/plugins/dataflow/model/utilities/channel.ts
  src/plugins/dataflow/model/utilities/node.ts
  src/plugins/dataflow/model/utilities/virtual-channel.ts
  src/plugins/dataflow/nodes/controls/sensor-value-control.tsx
  src/plugins/shared-variables/simulations/simulation-utilities.ts
  src/plugins/simulator/components/simulator-variable.tsx
  src/plugins/simulator/simulations/brainwaves-gripper/brainwaves-gripper.tsx
  src/plugins/simulator/simulations/terrarium/terrarium.tsx
Labels: rejected QA review, run regression

#2001 Fix preview link in CMS
  cms/src/preview-link-control.tsx
  src/models/stores/app-config-model.ts
  src/utilities/branch-utils.test.ts
  src/utilities/branch-utils.ts
Labels: approved QA review, run regression

#1966 182578812 xyplot multiple series
  cypress/e2e/clue/branch/student_tests/xy_plot_tool_spec.js
  cypress/support/elements/clue/XYPlotToolTile.js
  src/plugins/graph/adornments/connecting-lines/connecting-lines.tsx
  src/plugins/graph/components/graph-component.tsx
  src/plugins/graph/components/graph-wrapper-component.tsx
  src/plugins/graph/components/graph.tsx
  src/plugins/graph/components/legend/add-series-button.tsx
  src/plugins/graph/components/legend/multi-legend.scss
  src/plugins/graph/components/legend/multi-legend.tsx
  src/plugins/graph/components/simple-attribute-label.tsx
  src/plugins/graph/hooks/use-init-graph-layout.ts
  src/plugins/graph/hooks/use-point-locations.ts
  src/plugins/graph/imports/assets/add-series-icon.svg
  src/plugins/graph/imports/components/axis/components/axis-or-legend-attribute-menu.tsx
  src/plugins/graph/models/data-configuration-model.ts
  src/plugins/graph/models/graph-layout.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/graph/utilities/graph-utils.ts
Labels: approved QA review, run regression

#1996 185995457 view data as graph on table toolbar
  cypress/e2e/clue/branch/student_tests/data_card_tool_spec.js
  cypress/e2e/clue/branch/student_tests/table_tool_spec.js
  cypress/support/elements/clue/TableToolTile.js
  src/components/tiles/table/table-toolbar-buttons.tsx
  src/components/tiles/table/table-toolbar.tsx
  src/components/tiles/tile-api.tsx
  src/hooks/use-consumer-tile-linking.ts
  src/models/document/base-document-content.ts
  src/models/document/document-content.ts
  src/models/stores/app-config-model.ts
Labels: run regression

#2011 186263508 metadata categories
  src/plugins/graph/models/graph-controller.ts
  src/plugins/graph/models/graph-model.ts
Labels: approved QA review, run regression

#2009 fix: issues with filtering points on multiple-y plots
  src/plugins/graph/components/graph.tsx
  src/plugins/graph/models/data-configuration-model.ts
  src/plugins/graph/models/graph-model.ts
Labels: approved QA review, run regression

#2015 Failure Fixes
  .github/workflows/manual-regression.yml
  cypress/e2e/clue/branch/teacher_tests/teacher_chat_spec.js
  cypress/e2e/clue/full/teacher_tests/teacher_chat_spec.js
  cypress/e2e/clue/full/teacher_tests/teacher_dashboard_six_pack_spec.js
  cypress/e2e/clue/full/teacher_tests/teacher_dashboard_spec.js
  cypress/e2e/clue/full/teacher_tests/teacher_workspace_spec.js
  cypress/fixtures/teacher-dash-data.json
  cypress/support/elements/clue/ChatPanel.js
Labels: run regression

#2014 Multilegend should respect tile read-only status
  src/components/document/canvas.test.tsx
  src/components/document/canvas.tsx
  src/components/document/read-only-context.tsx
  src/components/four-up.tsx
  src/plugins/graph/components/graph-component.tsx
  src/plugins/graph/components/graph.tsx
  src/plugins/graph/components/legend/multi-legend.tsx
  src/plugins/graph/components/simple-attribute-label.tsx
Labels: approved QA review, run regression

#1997 186175823-numberline-has-edit-box
  cypress/e2e/clue/branch/student_tests/numberline_tool_spec.js
  cypress/support/elements/clue/NumberlineToolTile.js
  src/plugins/numberline/assets/numberline-arrow-left.svg
  src/plugins/numberline/assets/numberline-arrow-right.svg
  src/plugins/numberline/components/editable-numberline-value.tsx
  src/plugins/numberline/components/numberline-tile.scss
  src/plugins/numberline/components/numberline-tile.tsx
  src/plugins/numberline/models/numberline-content.ts
  src/plugins/numberline/numberline-tile-constants.ts
Labels: approved QA review, run regression

#2003 switch image map from MST to MobX
  src/components/tiles/geometry/geometry-content.tsx
  src/components/tiles/image/image-tile.tsx
  src/models/image-map.test.ts
  src/models/image-map.ts
  src/utilities/clipboard-utils.test.ts
  src/utilities/clipboard-utils.ts
  src/utilities/image-utils.ts
Labels: pending QA review, run regression

#2018 Customize switch to select tool after drawing
  cypress/e2e/clue/branch/student_tests/drawing_tool_spec.js
  src/plugins/drawing/components/drawing-layer.tsx
  src/plugins/drawing/components/drawing-tile.tsx
  src/plugins/drawing/objects/drawing-object.tsx
  src/plugins/drawing/objects/image.tsx
  src/plugins/drawing/objects/line.tsx
Labels: approved QA review, run regression

#2017 186227864 filter plotted series in legend
  src/plugins/graph/components/simple-attribute-label.tsx
  src/plugins/graph/imports/components/axis/components/axis-or-legend-attribute-menu.tsx
Labels: run regression

#2020 withoutUndo with opt out
  src/models/document/tile-row.ts
  src/models/history/without-undo.ts
Labels: run regression

#2023 Consolidate smaller cypress tests into larger ones to reduce test results
  .github/workflows/manual-regression.yml
  .github/workflows/regression-daily.yml
  cypress.config.ts
  cypress/e2e/clue/branch/student_tests/canvas_test_spec.js
  cypress/e2e/clue/branch/student_tests/data_card_tool_spec.js
  cypress/e2e/clue/branch/student_tests/datacard_merge_spec.js
  cypress/e2e/clue/branch/student_tests/dataflow_table_integration_test_spec.js
  cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js
  cypress/e2e/clue/branch/student_tests/diagram_tool_spec.js
  cypress/e2e/clue/branch/student_tests/drawing_tool_spec.js
  cypress/e2e/clue/branch/student_tests/duplicate_tile_spec.js
  cypress/e2e/clue/branch/student_tests/expression_tool_spec.js
  cypress/e2e/clue/branch/student_tests/graph_table_integraton_test_spec.js
  cypress/e2e/clue/branch/student_tests/graph_tool_spec.js
  cypress/e2e/clue/branch/student_tests/group_test_readonly_spec.js
  cypress/e2e/clue/branch/student_tests/group_test_spec.js
  cypress/e2e/clue/branch/student_tests/image_tool_spec.js
  cypress/e2e/clue/branch/student_tests/nav_panel_test_spec.js
  cypress/e2e/clue/branch/student_tests/numberline_tool_spec.js
  cypress/e2e/clue/branch/student_tests/shared_variables_test_spec.js
  cypress/e2e/clue/branch/student_tests/simulator_tile_spec.js
  cypress/e2e/clue/branch/student_tests/student_test_spec.js
  cypress/e2e/clue/branch/student_tests/table_tool_spec.js
  cypress/e2e/clue/branch/student_tests/text_tool_spec.js
  cypress/e2e/clue/branch/student_tests/workspace_test_spec.js
  cypress/e2e/clue/branch/teacher_tests/teacher_chat_spec.js
  cypress/e2e/clue/branch/teacher_tests/teacher_dashboard_4_quadrants_spec.js
  cypress/e2e/clue/branch/teacher_tests/teacher_network_spec.js
  cypress/e2e/clue/branch/teacher_tests/teacher_tagged_comments_spec.js
  cypress/e2e/clue/full/student_tests/group_chooser_spec.js
  cypress/e2e/clue/full/teacher_tests/teacher_workspace_spec.js
  cypress/e2e/clue/smoke/single_student_canvas_test.js
  cypress/e2e/common/header_test_spec.js
  cypress/support/commands.js
  cypress/support/elements/clue/cCanvas.js
Labels: run regression

#2024 fix: graph axis menus after resizing earlier rows
  src/plugins/data-card/components/case-attribute.tsx
  src/plugins/graph/components/attribute-label.tsx
  src/plugins/graph/components/simple-attribute-label.tsx
  src/plugins/graph/imports/components/axis/components/axis-or-legend-attribute-menu.tsx
Labels: approved QA review, run regression

#2022 XYPlot/Graph tile toolbar refactor
  cypress/e2e/clue/branch/student_tests/arrow_annotation_spec.js
  cypress/e2e/clue/branch/student_tests/xy_plot_tool_spec.js
  cypress/support/elements/clue/XYPlotToolTile.js
  src/clue/app-config.json
  src/components/tiles/text/toolbar/text-toolbar-button.tsx
  src/components/tiles/text/toolbar/text-toolbar-registration.tsx
  src/components/tiles/text/toolbar/text-toolbar.sass
  src/components/toolbar/tile-toolbar.test.tsx
  src/components/toolbar/tile-toolbar.tsx
  src/components/toolbar/toolbar-button-manager.tsx
  src/plugins/graph/components/graph-toolbar-registration.tsx
  src/plugins/graph/components/graph-toolbar.scss
  src/plugins/graph/components/graph-toolbar.tsx
  src/plugins/graph/components/graph-wrapper-component.tsx
Labels: approved QA review, run regression
