Repository concord-consortium/collaborative-learning, pull requests merged in 2024-01, with the labels that each got.

#2115 186610287 One Data Legend
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
  src/plugins/graph/components/legend/add-series-button.tsx
  src/plugins/graph/components/legend/layer-legend.tsx
  src/plugins/graph/components/legend/multi-legend.scss
  src/plugins/graph/components/legend/multi-legend.tsx
  src/plugins/graph/components/legend/variable-function-legend.tsx
  src/plugins/graph/components/legend/variable-selection.scss
  src/plugins/graph/components/legend/variable-selection.tsx
  src/plugins/shared-variables/shared-variables.ts
Labels: approved QA review, run regression

#2117 186714042 ramp transform
  cypress/e2e/functional/tile_tests/dataflow_tool_spec.js
  src/plugins/dataflow/model/utilities/node.ts
  src/plugins/dataflow/nodes/factories/transform-rete-node-factory.tsx
Labels: approved QA review, run regression

#2110 186506881 sort tab thumbnail handlers
  src/components/app.tsx
  src/components/chat/chat-panel-header.scss
  src/components/document/sort-work-view.scss
  src/components/document/sort-work-view.tsx
  src/components/navigation/nav-tab-panel.tsx
  src/components/navigation/sort-work-header-dropdown.scss
  src/components/navigation/sort-work-header.tsx
  src/components/thumbnail/collapsible-document-section.tsx
  src/components/thumbnail/decorated-document-thumbnail-item.tsx
  src/components/thumbnail/document-collection-list.tsx
  src/components/thumbnail/documents-type-collection.tsx
  src/lib/db-listeners/db-student-personal-docs-listener.ts
  src/lib/db-listeners/index.ts
  src/lib/debug.ts
  src/models/document/document-types.ts
  src/models/view/nav-tabs.ts
  src/public/curriculum/example-curriculum/example-config-subtabs.json
Labels: approved QA review, run regression

#2119 186660488 Colored Variable Traces
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-component.scss
  src/plugins/graph/adornments/plotted-function/plotted-variables/plotted-variables-adornment-component.tsx
  src/plugins/graph/components/graph-clue-styles.scss
  src/plugins/graph/components/legend/legend-dropdown.scss
  src/plugins/graph/components/legend/legend-dropdown.tsx
  src/plugins/graph/components/legend/multi-legend.scss
  src/plugins/graph/components/legend/variable-function-legend.tsx
  src/plugins/graph/components/legend/variable-selection.tsx
  src/plugins/graph/imports/components/axis/components/axis-or-legend-attribute-menu.tsx
  src/plugins/graph/models/graph-model.test.ts
  src/plugins/graph/models/graph-model.ts
  src/utilities/color-utils.ts
Labels: approved QA review, run regression

#2114 switch to using await
  src/components/document/canvas.test.tsx
  src/lib/auth.ts
Labels: run regression

#2126 xy_plot_tool_spec should test for link multiple dataset button
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
Labels: approved QA review, run regression

#2128 Tile Restore Automation
  cypress/e2e/functional/tile_tests/data_card_tool_spec.js
  cypress/e2e/functional/tile_tests/diagram_tool_spec.js
  cypress/e2e/functional/tile_tests/drawing_tool_spec.js
  cypress/e2e/functional/tile_tests/expression_tool_spec.js
  cypress/e2e/functional/tile_tests/geometry_tool_spec.js
  cypress/e2e/functional/tile_tests/numberline_tool_spec.js
  cypress/e2e/functional/tile_tests/simulator_tile_spec.js
  cypress/e2e/functional/tile_tests/table_tool_spec.js
  cypress/e2e/functional/tile_tests/text_tool_spec.js
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
Labels: run regression

#2129 Dialog wording changes
  cypress/e2e/functional/tile_tests/data_card_tool_spec.js
  cypress/e2e/functional/tile_tests/table_tool_spec.js
  cypress/support/commands.js
  cypress/support/elements/tile/XYPlotToolTile.js
  src/hooks/use-link-consumer-tile-dialog.tsx
  src/hooks/use-link-provider-tile-dialog.tsx
Labels: approved QA review, run regression

#2121 186345543 XY Plot Shared Variables Plugin
  docs/variables.md
  src/components/document/read-only-context.tsx
  src/plugins/graph/adornments/adornment-content-info.ts
  src/plugins/graph/adornments/adornment-models.test.ts
  src/plugins/graph/adornments/adornment-types.ts
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-component.tsx
  src/plugins/graph/components/graph-clue-styles.scss
  src/plugins/graph/components/graph.tsx
  src/plugins/graph/components/legend/layer-legend.tsx
  src/plugins/graph/components/legend/legend-constants.ts
  src/plugins/graph/components/legend/legend-dropdown.tsx
  src/plugins/graph/components/legend/legend-registration.ts
  src/plugins/graph/components/legend/legend-types.ts
  src/plugins/graph/components/legend/multi-legend.scss
  src/plugins/graph/components/legend/multi-legend.tsx
  src/plugins/graph/imports/components/axis/components/axis-or-legend-attribute-menu.tsx
  src/plugins/graph/models/graph-model.test.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/graph/register-adornment-types.ts
  src/plugins/shared-variables/graph/legend/variable-function-legend.tsx
  src/plugins/shared-variables/graph/legend/variable-selection.tsx
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-component.tsx
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-model.ts
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-registration.tsx
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-types.ts
  src/plugins/shared-variables/shared-variables-registration.ts
Labels: approved QA review, run regression

#2124 Fix table-dataset-linking bug
  src/hooks/use-consumer-tile-linking.ts
Labels: approved QA review, run regression

#2102 Set axis domain for variables plot
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
  src/plugins/graph/adornments/adornment-models.ts
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-model.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-component.tsx
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-model.ts
Labels: approved QA review, run regression

#2113 186506848 sort by name and group
  src/components/document/sort-work-view.scss
  src/components/document/sort-work-view.tsx
  src/components/navigation/sort-work-header-dropdown.scss
  src/hooks/use-document-caption.tsx
Labels: approved QA review, run regression

#2134 Variables plotting performance improvement
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-model.ts
Labels: approved QA review, run regression

#2133 Add variable-value readout point to graph
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-component.tsx
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables.scss
Labels: approved QA review, run regression

#2127 186472626 personal doc visibility
  cypress/e2e/functional/document_tests/canvas_test_spec.js
  src/components/document/document.tsx
  src/components/navigation/problem-tab-content.tsx
  src/components/utilities/toggle-control.tsx
  src/hooks/use-document-sync-to-firebase.test.ts
  src/hooks/use-document-sync-to-firebase.ts
  src/lib/db-types.ts
  src/lib/db.ts
  src/models/stores/documents.ts
Labels: approved QA review, run regression

#2123 186719432 open docs from sort work tab
  cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js
  src/components/document/sort-work-document-area.tsx
  src/components/document/sort-work-view.scss
  src/components/document/sort-work-view.tsx
  src/components/navigation/document-view.tsx
  src/components/navigation/nav-tab-panel.tsx
Labels: pending QA review, run regression

#2130 add OAuth2 support for launching CLUE directly
  docs/oauth2.md
  package-lock.json
  package.json
  src/index.tsx
  src/initialize-app.tsx
  src/lib/auth.test.ts
  src/lib/auth.ts
  src/lib/portal-api.ts
  src/utilities/auth-utils.ts
  src/utilities/url-params.ts
Labels: approved QA review, run regression

#2138 186811130 enable sort work listeners
  src/lib/db-listeners/db-student-personal-docs-listener.ts
Labels: approved QA review, run regression

#2141 only show personal doc share toggle if sort-work is enabled
  cypress/e2e/functional/document_tests/canvas_test_spec.js
  src/components/document/document.tsx
Labels: approved QA review, run regression

#2143 185855379 Increase Allowed Zoom Out and Prevent Panning while Dragging Nodes
  package-lock.json
  package.json
  src/plugins/diagram-viewer/diagram-types.ts
Labels: approved QA review, run regression

#2140 Change variable values by dragging points
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
  src/plugins/graph/adornments/plotted-function/plotted-function-adornment-model.ts
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-component.tsx
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables.scss
  src/plugins/shared-variables/shared-variables.ts
Labels: approved QA review, run regression

#2144 186420492 Axis Labels
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
  src/components/tiles/basic-editable-tile-title.tsx
  src/components/tiles/editable-tile-title.tsx
  src/components/tiles/geometry/geometry-content.tsx
  src/components/tiles/image/image-tile.tsx
  src/plugins/dataflow/components/dataflow-tile.tsx
  src/plugins/diagram-viewer/diagram-tile.tsx
  src/plugins/drawing/components/drawing-tile.tsx
  src/plugins/graph/components/attribute-label.scss
  src/plugins/graph/components/attribute-label.tsx
  src/plugins/graph/components/axis-end-components.scss
  src/plugins/graph/components/axis-end-components.tsx
  src/plugins/graph/components/graph-axis.tsx
  src/plugins/graph/components/graph-wrapper-component.tsx
  src/plugins/graph/components/graph.scss
  src/plugins/graph/components/input-textbox.tsx
  src/plugins/graph/graph-types.ts
  src/plugins/graph/imports/components/axis/axis-types.ts
  src/plugins/graph/imports/components/axis/hooks/use-axis.ts
  src/plugins/graph/imports/components/axis/hooks/use-sub-axis.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/numberline/components/numberline-tile.tsx
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-registration.tsx
  src/plugins/simulator/components/simulator-tile.tsx
Labels: approved QA review, run regression

#2150 Consistent rounding
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-component.tsx
Labels: approved QA review, run regression

#2149 186631894 sort work for students with isPrivate calc
  README.md
  src/components/document/doc-list-debug.scss
  src/components/document/doc-list-debug.tsx
  src/components/document/sort-work-view.tsx
  src/components/thumbnail/thumbnail-document-item.tsx
  src/lib/debug.ts
  src/models/document/document.ts
Labels: pending QA review, run regression

#2151 autoscale adjustments
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  src/plugins/graph/graph-types.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-model.ts
Labels: pending QA review, run regression

#2152 bring demo temperature data back in as an option on temp sensor
  cypress/e2e/functional/tile_tests/dataflow_tool_spec.js
  cypress/e2e/functional/tile_tests/simulator_tile_spec.js
  src/plugins/dataflow/model/utilities/virtual-channel.ts
Labels: approved QA review, run regression

#2155 Fix failing datacard cypress tests
  cypress/e2e/functional/tile_tests/data_card_tool_spec.js
  cypress/support/elements/tile/DataCardToolTile.js
Labels: run regression

#2147 186665118 sort by strategy
  cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js
  src/components/chat/commented-documents.tsx
  src/components/document/sort-work-view.tsx
  src/components/navigation/sort-work-header-dropdown.scss
  src/models/stores/sorted-documents.test.ts
  src/models/stores/sorted-documents.ts
  src/models/stores/stores.ts
Labels: approved QA review, run regression

#2154 186665188 close button
  cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js
  src/assets/icons/close/close.svg
  src/components/document/sort-work-document-area.tsx
  src/components/document/sort-work-view.scss
  src/components/navigation/document-view.tsx
  src/components/navigation/nav-tab-panel.sass
  src/components/navigation/section-document-or-browser.scss
Labels: approved QA review, run regression

#2156 Type-ahead: match any substring
  cypress/e2e/functional/tile_tests/data_card_tool_spec.js
  src/plugins/data-card/components/case-attribute.tsx
Labels: approved QA review, run regression

#2148 186506915 sort by bookmarks starred
  cypress/e2e/functional/document_tests/canvas_test_spec.js
  cypress/e2e/functional/document_tests/nav_panel_test_spec.js
  cypress/e2e/functional/teacher_tests/teacher_curation_spec.js
  src/assets/thumbnail-bookmark-icon.svg
  src/clue/app-config.json
  src/components/document/sort-work-view.tsx
  src/components/four-up.sass
  src/components/four-up.tsx
  src/components/navigation/document-view.tsx
  src/components/navigation/section-document-or-browser.tsx
  src/components/thumbnail/document-type-collection.sass
  src/components/thumbnail/thumbnail-document-item.tsx
  src/models/stores/sorted-documents.ts
  src/models/view/nav-tabs.ts
Labels: approved QA review, run regression

#2158 Use a new bookmarks store
  README.md
  docs/bookmarks.md
  package-lock.json
  package.json
  src/components/document/document.tsx
  src/components/four-up.tsx
  src/components/navigation/document-view.tsx
  src/components/thumbnail/decorated-document-thumbnail-item.tsx
  src/components/thumbnail/document-type-collection.sass
  src/components/thumbnail/documents-type-collection.tsx
  src/components/thumbnail/thumbnail-document-item.tsx
  src/lib/db-listeners/db-bookmarks-listener.ts
  src/lib/db-listeners/db-other-docs-listener.ts
  src/lib/db-listeners/db-problem-documents-listener.ts
  src/lib/db-listeners/db-publications-listener.ts
  src/lib/db-listeners/db-stars-listener.ts
  src/lib/db-listeners/index.ts
  src/lib/db-listeners/sync-stars.ts
  src/lib/db.ts
  src/lib/debug.ts
  src/models/document/document.test.ts
  src/models/document/document.ts
  src/models/stores/base-stores-types.ts
  src/models/stores/bookmarks.test.ts
  src/models/stores/bookmarks.ts
  src/models/stores/sorted-documents.ts
  src/models/stores/stores.ts
Labels: run regression

#2162 186472564 XY Plots Always have Both Axes
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  src/plugins/graph/components/legend/layer-legend.tsx
  src/plugins/graph/components/simple-attribute-label.tsx
  src/plugins/graph/imports/components/axis/components/axis-or-legend-attribute-menu.tsx
Labels: approved QA review, run regression

#2163 Show and log loading messages
  README.md
  src/components/app.tsx
  src/components/document/document-workspace.tsx
  src/components/group/group-chooser.tsx
  src/index.html
  src/index.scss
  src/index.tsx
  src/lib/debug.ts
  src/models/stores/persistent-ui.ts
  src/models/stores/stores.ts
  src/utilities/loading-utils.ts
Labels: run regression

#2157 186506936 class work tools sort
  cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js
  src/components/document/sort-work-view.tsx
  src/models/document/base-document-content.ts
  src/models/stores/sorted-documents.ts
Labels: run regression
