Repository concord-consortium/collaborative-learning, pull requests merged in 2024-03, with the labels that each got.

#2205 curriculum config refactoring
  cms/src/cms-constants.ts
  cms/src/init-cms.ts
  cms/src/preview-link-control.tsx
  src/clue/app-config.json
  src/clue/curriculum-config.json
  src/components/app.tsx
  src/components/chat/chat-panel.test.tsx
  src/components/chat/chat-thread.test.tsx
  src/components/chat/comment-card.test.tsx
  src/components/document/canvas.tsx
  src/components/tiles/tile-component.tsx
  src/hooks/use-stores.test.ts
  src/initialize-app.tsx
  src/lib/auth.test.ts
  src/lib/auth.ts
  src/lib/portal-api.test.ts
  src/lib/portal-api.ts
  src/models/curriculum/unit-utils.ts
  src/models/curriculum/unit.ts
  src/models/mst.test.ts
  src/models/stores/app-config-model.test.ts
  src/models/stores/app-config-model.ts
  src/models/stores/base-stores-types.ts
  src/models/stores/curriculum-config.test.ts
  src/models/stores/curriculum-config.ts
  src/models/stores/spec-app-config.ts
  src/models/stores/stores.test.ts
  src/models/stores/stores.ts
  src/plugins/drawing/model/drawing-content.test.ts
  src/test-fixtures/sample-portal-offerings.ts
  src/utilities/auth-utils.ts
  src/utilities/url-params.ts
  src/utilities/url-utils.ts
Labels: run regression

#2207 #186813644 - **[Exemplar]** Sort header is sticky
  src/components/document/sort-work-view.scss
  src/components/document/sort-work-view.tsx
  src/components/thumbnail/document-type-collection.sass
Labels: run regression

#2214 187080552 teacher name prefix
  src/hooks/use-document-caption.tsx
Labels: run regression

#2217 Fix cypress test failure due to merge
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
Labels: run regression

#2215 fix rollbar errors from setPositions
  src/plugins/graph/utilities/graph-utils.ts
Labels: run regression

#2222 fix cypress copy tiles and expression tile test
  .github/workflows/ci-regression.yml
  .github/workflows/ci.yml
  .github/workflows/manual-regression.yml
  .github/workflows/regression-daily.yml
  cypress/e2e/functional/document_tests/tiles_copy_test_spec.js
  cypress/e2e/functional/tile_tests/expression_tool_spec.js
  cypress/support/elements/tile/ExpressionToolTile.js
  src/plugins/expression/expression-tile.test.tsx
  src/plugins/expression/expression-tile.tsx
Labels: run regression

#2216 186993522 only load current problem
  cms/src/cms-collections.ts
  cms/src/preview-link-control.tsx
  docs/launch-sequence-abstract.md
  docs/launch-sequence.md
  src/components/document/document-workspace.tsx
  src/models/curriculum/problem.test.ts
  src/models/curriculum/problem.ts
  src/models/curriculum/section.ts
  src/models/curriculum/support.ts
  src/models/curriculum/unit-utils.ts
  src/models/curriculum/unit.ts
  src/models/stores/curriculum-config.ts
  src/models/stores/stores.ts
  src/models/tiles/log/log-comment-event.test.ts
Labels: run regression

#2219 update CMS to Decap and React 18
  cms/package-lock.json
  cms/package.json
  cms/src/cms-collections.ts
  cms/src/cms-url-params.ts
  cms/src/iframe-control.tsx
  cms/src/init-cms.ts
  cms/src/preview-link-control.tsx
  cms/tsconfig.json
Labels: run regression

#2213 Add points by hand toolbar button
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
  src/assets/edit.svg
  src/clue/app-config.json
  src/components/utilities/editable-label-with-button.scss
  src/components/utilities/editable-label-with-button.tsx
  src/models/data/data-set.ts
  src/plugins/graph/assets/add-points-by-hand-icon.svg
  src/plugins/graph/components/graph-toolbar-registration.tsx
  src/plugins/graph/components/legend/layer-legend.tsx
  src/plugins/graph/components/legend/multi-legend.scss
  src/plugins/graph/models/graph-layer-model.ts
  src/plugins/graph/models/graph-model.test.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/graph/utilities/graph-utils.test.ts
  src/public/demo/units/qa-config-subtabs/content.json
  src/public/demo/units/qa/content.json
Labels: approved QA review, run regression

#2228 Fix copy graph
  cypress/e2e/functional/tile_tests/duplicate_tile_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
Labels: pending QA review, run regression

#2232 Delete points from graph
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  src/clue/app-config.json
  src/components/utilities/editable-label-with-button.tsx
  src/models/data/data-set.ts
  src/plugins/graph/assets/delete-selection-icon.svg
  src/plugins/graph/components/background.tsx
  src/plugins/graph/components/graph-toolbar-registration.tsx
  src/plugins/graph/components/graph-wrapper-component.tsx
  src/plugins/graph/components/input-textbox.tsx
  src/plugins/graph/models/graph-layer-model.ts
  src/plugins/graph/models/graph-model.ts
  src/public/demo/units/qa-config-subtabs/content.json
Labels: pending QA review, run regression

#2230 Add movable line to graph
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
  docs/unit-configuration.md
  src/clue/app-config.json
  src/plugins/graph/adornments/adornment.tsx
  src/plugins/graph/adornments/movable-line/movable-line-model.ts
  src/plugins/graph/adornments/movable-line/movable-line.tsx
  src/plugins/graph/assets/movable-line-icon.svg
  src/plugins/graph/components/graph-toolbar-registration.tsx
  src/plugins/graph/components/graph.tsx
  src/plugins/graph/models/graph-model.test.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/shared-variables/shared-variables-registration.ts
  src/public/demo/units/qa-config-subtabs/content.json
Labels: pending QA review, run regression

#2231 make image url match more strict
  src/models/image-map.test.ts
  src/models/image-map.ts
Labels: run regression

#2233 Add Cypress test of linking table with expression
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
Labels: pending QA review, run regression

#2240 notify slack when builds of master fail
  .github/workflows/ci-regression.yml
  .github/workflows/ci.yml
  .github/workflows/regression-daily.yml
Labels: run regression

#2241 187135761-replace-x-icon-for-delete-2
  src/assets/icons/delete/delete-selection-icon.svg
  src/clue/assets/icons/delete-tool.svg
  src/plugins/data-card/assets/delete-selection-icon.svg
  src/plugins/expression/expression-toolbar.scss
  src/plugins/graph/assets/remove-data-icon.svg
  src/plugins/numberline/assets/numberline-toolbar-delete-icon.svg
  src/plugins/numberline/components/editable-numberline-value.tsx
  src/plugins/numberline/components/numberline-tile.scss
  src/plugins/numberline/components/numberline-tile.tsx
Labels: run regression

#2218 186939433 display exemplars
  README.md
  cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js
  cypress/support/elements/common/SortedWork.js
  docs/launch-sequence.md
  src/clue/curriculum-config.json
  src/hooks/use-document-caption.tsx
  src/lib/auth.test.ts
  src/lib/portal-api.test.ts
  src/models/curriculum/problem.test.ts
  src/models/curriculum/problem.ts
  src/models/document/document-types.ts
  src/models/stores/class.ts
  src/models/stores/create-exemplar-docs.test.ts
  src/models/stores/create-exemplar-docs.ts
  src/models/stores/curriculum-config.test.ts
  src/models/stores/curriculum-config.ts
  src/models/stores/stores.test.ts
  src/models/stores/stores.ts
  src/models/stores/user-types.ts
  src/public/demo/units/qa-config-subtabs/content.json
  src/public/demo/units/qa-config-subtabs/exemplars/investigation-1/problem-1/exemplar-1/content.json
  src/public/demo/units/qa-config-subtabs/sections/investigation-1/problem-1/first/content.json
  src/public/demo/units/qa-config-subtabs/sections/investigation-1/problem-1/second/content.json
  src/public/demo/units/qa-config-subtabs/sections/investigation-1/problem-1/third/content.json
  src/public/demo/units/qa-config-subtabs/sections/investigation-1/problem-2/first/content.json
  src/public/demo/units/qa-config-subtabs/sections/investigation-1/problem-2/second/content.json
  src/public/demo/units/qa-config-subtabs/sections/investigation-1/problem-2/third/content.json
Labels: run regression

#2223 187185137 exemplar authored tag
  cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js
  cypress/support/elements/common/ChatPanel.js
  cypress/support/elements/common/SortedWork.js
  src/models/stores/create-exemplar-docs.ts
  src/models/stores/sorted-documents.ts
  src/public/demo/units/qa-config-subtabs/content.json
  src/public/demo/units/qa-config-subtabs/exemplars/investigation-1/problem-1/exemplar-1/content.json
Labels: run regression

#2239 autoscale changes
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  src/plugins/graph/components/graph-axis.tsx
  src/plugins/graph/components/graph-component.tsx
  src/plugins/graph/components/graph.tsx
  src/plugins/graph/components/scatterdots.tsx
  src/plugins/graph/d3-types.ts
  src/plugins/graph/hooks/use-graph-model.ts
  src/plugins/graph/hooks/use-plot.ts
  src/plugins/graph/imports/components/axis/models/axis-model.ts
  src/plugins/graph/models/graph-controller.ts
  src/plugins/graph/models/graph-layer-model.ts
  src/plugins/graph/utilities/graph-utils.ts
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-component.tsx
  src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-model.ts
  src/plugins/shared-variables/shared-variables-registration.ts
Labels: run regression

#2242 "View as graph" adds a layer when possible
  docs/unit-configuration.md
  src/hooks/use-consumer-tile-linking.ts
  src/models/tiles/geometry/geometry-registration.ts
  src/models/tiles/tile-content-info.ts
  src/plugins/graph/graph-registration.ts
  src/plugins/graph/models/graph-model.ts
Labels: pending QA review, run regression
