Repository concord-consortium/collaborative-learning, pull requests merged in 2024-04, with the labels that each got.

#2244 Movable line update
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
  src/plugins/graph/adornments/movable-line/movable-line-model.test.ts
  src/plugins/graph/adornments/movable-line/movable-line-model.ts
  src/plugins/graph/adornments/movable-line/movable-line.scss
  src/plugins/graph/adornments/movable-line/movable-line.tsx
  src/plugins/graph/assets/movable-line-icon.svg
  src/plugins/graph/hooks/use-movables.ts
  src/plugins/graph/utilities/graph-utils.ts
Labels: run regression

#2248 Movable line sparrows
  cypress/e2e/functional/tile_tests/arrow_annotation_spec.js
  cypress/support/elements/tile/XYPlotToolTile.js
  docs/annotations.md
  src/plugins/graph/adornments/movable-line/movable-line-model.ts
  src/plugins/graph/adornments/movable-line/movable-line.tsx
  src/plugins/graph/components/graph-wrapper-component.tsx
  src/plugins/graph/graph-types.ts
  src/plugins/graph/hooks/use-location-setter-context.ts
  src/plugins/graph/models/graph-model.ts
Labels: run regression

#2253 Fixes for categorical graphs
  cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
  src/plugins/graph/adornments/connecting-lines/connecting-lines.tsx
  src/plugins/graph/components/graph-wrapper-component.tsx
  src/plugins/graph/components/graph.scss
  src/plugins/graph/components/graph.tsx
  src/plugins/graph/hooks/use-point-locations.ts
  src/plugins/graph/imports/components/axis/components/axis-or-legend-attribute-menu.tsx
  src/plugins/graph/models/data-configuration-model.ts
  src/plugins/graph/models/graph-controller.ts
  src/plugins/graph/models/graph-layer-model.ts
  src/plugins/graph/models/graph-model.ts
  src/plugins/graph/utilities/graph-utils.ts
Labels: run regression

#2252 update shared react components
  package-lock.json
  package.json
Labels: run regression

#2254 Per-student exemplar visibility.
  docs/unit-configuration.md
  src/clue/app-config.json
  src/components/thumbnail/thumbnail-document-item.tsx
  src/lib/db-listeners/db-exemplars-listener.ts
  src/lib/db-listeners/index.ts
  src/lib/firebase.ts
  src/models/document/document-types.ts
  src/models/document/document.test.ts
  src/models/document/document.ts
  src/models/stores/configuration-manager.ts
  src/models/stores/create-exemplar-docs.ts
  src/models/stores/documents.ts
  src/models/stores/unit-configuration.ts
  src/public/demo/units/qa-config-subtabs/content.json
Labels: run regression

#2263 handle node positions
  cypress/e2e/functional/tile_tests/dataflow_tool_spec.js
  src/plugins/dataflow/components/dataflow-program.tsx
  src/plugins/dataflow/components/ui/dataflow-drop-zone.tsx
  src/plugins/dataflow/model/dataflow-program-model.ts
  src/plugins/dataflow/nodes/dataflow-node-plot.tsx
  src/plugins/dataflow/nodes/node-editor-mst.ts
  src/plugins/dataflow/nodes/utilities/view-utilities.ts
Labels: run regression, rete-v2

#2267 readOnly Data flow support
  src/plugins/dataflow/components/dataflow-program.tsx
  src/plugins/dataflow/nodes/base-node.ts
  src/plugins/dataflow/nodes/control-node.ts
  src/plugins/dataflow/nodes/controls/demo-outputs/humidifier-animation.tsx
  src/plugins/dataflow/nodes/controls/dropdown-list-control.tsx
  src/plugins/dataflow/nodes/controls/input-value-control.tsx
  src/plugins/dataflow/nodes/controls/num-control.tsx
  src/plugins/dataflow/nodes/controls/num-units-control.tsx
  src/plugins/dataflow/nodes/controls/value-control.tsx
  src/plugins/dataflow/nodes/counter-node.ts
  src/plugins/dataflow/nodes/demo-output-node.ts
  src/plugins/dataflow/nodes/generator-node.ts
  src/plugins/dataflow/nodes/live-output-node.ts
  src/plugins/dataflow/nodes/logic-node.ts
  src/plugins/dataflow/nodes/math-node.ts
  src/plugins/dataflow/nodes/node-editor-mst.ts
  src/plugins/dataflow/nodes/service-types.ts
  src/plugins/dataflow/nodes/timer-node.ts
  src/plugins/dataflow/nodes/transform-node.ts
  src/plugins/dataflow/nodes/utilities/view-utilities.ts
Labels: run regression, rete-v2

#2258 Properly display text objects in 4-up drawings
  src/plugins/drawing/components/wrapped-svg-text.tsx
Labels: run regression

#2256 exemplars on action
  cypress/e2e/functional/document_tests/exemplar_test_spec.js
  cypress/support/elements/common/SortedWork.js
  src/components/tiles/text/text-tile.tsx
  src/components/workspace/workspace.tsx
  src/lib/db-listeners/db-exemplars-listener.ts
  src/lib/db.ts
  src/lib/firebase.ts
  src/lib/logger.ts
  src/models/stores/documents.ts
  src/models/stores/exemplar-controller-rules.ts
  src/models/stores/exemplar-controller.ts
  src/models/stores/stores.ts
  src/models/tiles/text/text-content.ts
  src/utilities/string-utils.ts
Labels: run regression

#2257 exemplar alert
  cypress/e2e/functional/document_tests/exemplar_test_spec.js
  cypress/support/elements/common/SortedWork.js
  cypress/support/elements/common/cCanvas.js
  src/components/document/document.tsx
  src/components/document/sort-work-view.tsx
  src/components/navigation/document-view.tsx
  src/components/navigation/section-document-or-browser.tsx
  src/lib/logger-types.ts
  src/models/curriculum/support.ts
  src/models/document/log-document-event.ts
  src/models/document/log-exemplar-document-event.ts
  src/models/stores/exemplar-controller.ts
  src/models/stores/persistent-ui.ts
Labels: run regression

#2271 187382897-finish-playback
  src/plugins/dataflow/components/dataflow-program.tsx
  src/plugins/dataflow/components/dataflow-tile.tsx
  src/plugins/dataflow/components/ui/dataflow-drop-zone.tsx
  src/plugins/dataflow/nodes/base-node.ts
  src/plugins/dataflow/nodes/control-node.ts
  src/plugins/dataflow/nodes/dataflow-node.tsx
  src/plugins/dataflow/nodes/delete.tsx
  src/plugins/dataflow/nodes/logic-node.ts
  src/plugins/dataflow/nodes/math-node.ts
  src/plugins/dataflow/nodes/node-editor-mst.ts
  src/plugins/dataflow/nodes/rete-manager.tsx
  src/plugins/dataflow/nodes/service-types.ts
  src/plugins/dataflow/nodes/transform-node.ts
  src/plugins/dataflow/nodes/utilities/view-utilities.ts
  src/plugins/dataflow/utilities/playback-utils.ts
Labels: run regression, rete-v2

#2270 add secs to hold block field
  src/plugins/dataflow/nodes/control-node.ts
  src/plugins/dataflow/nodes/controls/num-control.tsx
Labels: run regression, rete-v2

#2272 add value and plot to sensor
  cypress/e2e/functional/tile_tests/dataflow_tool_spec.js
  cypress/e2e/functional/tile_tests/simulator_tile_spec.js
  src/plugins/dataflow/nodes/base-node.ts
  src/plugins/dataflow/nodes/controls/value-with-units-control.sass
  src/plugins/dataflow/nodes/controls/value-with-units-control.tsx
  src/plugins/dataflow/nodes/generator-node.ts
  src/plugins/dataflow/nodes/rete-manager.tsx
  src/plugins/dataflow/nodes/rete-scheme.ts
  src/plugins/dataflow/nodes/sensor-node.ts
Labels: run regression, rete-v2

#2274 optimize Dataflow tick
  src/plugins/dataflow/model/dataflow-program-model.ts
  src/plugins/dataflow/nodes/engine/dataflow-engine.ts
  src/plugins/dataflow/nodes/engine/dataflow.ts
  src/plugins/dataflow/nodes/engine/readme.md
  src/plugins/dataflow/nodes/engine/utils/cache.ts
  src/plugins/dataflow/nodes/node-editor-mst.ts
  src/plugins/dataflow/nodes/rete-manager.tsx
Labels: run regression, rete-v2

#2275 log same events in rete v2
  src/plugins/dataflow/nodes/controls/plot-button-control.tsx
  src/plugins/dataflow/nodes/rete-manager.tsx
Labels: run regression, rete-v2

#2277 process in read only mode too
  src/lib/debug.ts
  src/models/tiles/tile-model.ts
  src/plugins/dataflow/components/dataflow-program.tsx
  src/plugins/dataflow/model/dataflow-program-model.ts
  src/plugins/dataflow/nodes/base-node.ts
  src/plugins/dataflow/nodes/control-node.ts
  src/plugins/dataflow/nodes/controls/dropdown-list-control.tsx
  src/plugins/dataflow/nodes/controls/input-value-control.tsx
  src/plugins/dataflow/nodes/controls/num-control.tsx
  src/plugins/dataflow/nodes/controls/num-units-control.tsx
  src/plugins/dataflow/nodes/dataflow-node-plot-types.ts
  src/plugins/dataflow/nodes/dataflow-node-plot.tsx
  src/plugins/dataflow/nodes/demo-output-node.ts
  src/plugins/dataflow/nodes/generator-node.ts
  src/plugins/dataflow/nodes/live-output-node.ts
  src/plugins/dataflow/nodes/logic-node.ts
  src/plugins/dataflow/nodes/math-node.ts
  src/plugins/dataflow/nodes/number-node.ts
  src/plugins/dataflow/nodes/rete-manager.tsx
  src/plugins/dataflow/nodes/sensor-node.ts
  src/plugins/dataflow/nodes/service-types.ts
  src/plugins/dataflow/nodes/timer-node.ts
  src/plugins/dataflow/nodes/transform-node.ts
Labels: run regression, rete-v2

#2278 update live output node to not update state on tick
  docs/dataflow.md
  src/plugins/dataflow/model/utilities/node.ts
  src/plugins/dataflow/nodes/control-node.ts
  src/plugins/dataflow/nodes/controls/dropdown-list-control.tsx
  src/plugins/dataflow/nodes/demo-output-node.ts
  src/plugins/dataflow/nodes/generator-node.ts
  src/plugins/dataflow/nodes/live-output-node.ts
  src/plugins/dataflow/nodes/logic-node.ts
  src/plugins/dataflow/nodes/math-node.ts
  src/plugins/dataflow/nodes/sensor-node.ts
  src/plugins/dataflow/nodes/transform-node.ts
Labels: run regression, rete-v2

#2279 tick entries
  cypress/e2e/functional/tile_tests/simulator_tile_spec.js
  docs/dataflow.md
  src/plugins/dataflow/components/dataflow-program.tsx
  src/plugins/dataflow/model/dataflow-program-model.ts
  src/plugins/dataflow/nodes/base-node.ts
  src/plugins/dataflow/nodes/control-node.ts
  src/plugins/dataflow/nodes/dataflow-node-plot.tsx
  src/plugins/dataflow/nodes/dataflow-node.tsx
  src/plugins/dataflow/nodes/live-output-node.ts
  src/plugins/dataflow/nodes/rete-manager.tsx
  src/plugins/dataflow/nodes/service-types.ts
  src/plugins/dataflow/nodes/transform-node.ts
  src/plugins/dataflow/utilities/playback-utils.ts
Labels: run regression, rete-v2

#2259 Add dataflow and simulation servo
  cypress.config.ts
  cypress/e2e/functional/tile_tests/dataflow_tool_spec.js
  cypress/e2e/functional/tile_tests/simulator_tile_spec.js
  src/models/stores/serial.ts
  src/plugins/dataflow/model/utilities/node.ts
  src/plugins/dataflow/nodes/base-node.ts
  src/plugins/dataflow/nodes/live-output-node.ts
  src/plugins/simulator/simulations/potentiometer-servo/potentiometer-servo.tsx
  src/plugins/simulator/simulations/simulation-utilities.ts
Labels: run regression, rete-v2, rete-v2-feature

#2264 Dataflow toolbar (Rete 2 version)
  cypress/e2e/functional/tile_tests/dataflow_table_graph_integration_test_spec.js
  cypress/e2e/functional/tile_tests/dataflow_table_integration_test_spec.js
  cypress/e2e/functional/tile_tests/dataflow_tool_spec.js
  docs/unit-configuration.md
  src/clue/app-config.json
  src/components/toolbar/data-set-link-button.tsx
  src/components/toolbar/data-set-view-button.tsx
  src/plugins/dataflow/components/dataflow-tile.tsx
  src/plugins/dataflow/components/ui/dataflow-program-link-table-button.tsx
  src/plugins/dataflow/dataflow-toolbar-registration.tsx
  src/plugins/dataflow/model/dataflow-content.ts
Labels: run regression, rete-v2, rete-v2-feature

#2260 rename Sensor to Input
  cypress/e2e/functional/tile_tests/dataflow_tool_spec.js
  cypress/e2e/functional/tile_tests/simulator_tile_spec.js
  src/models/stores/serial.ts
  src/plugins/dataflow-tool/arduino/ccemgfsr/ccemgfsr.ino
  src/plugins/dataflow/assets/icons/sensor/sensor-emg-icon.svg
  src/plugins/dataflow/model/utilities/channel.ts
  src/plugins/dataflow/model/utilities/node.ts
  src/plugins/dataflow/model/utilities/virtual-channel.ts
  src/plugins/dataflow/nodes/live-output-node.ts
  src/plugins/dataflow/nodes/sensor-node.ts
  src/plugins/shared-assets/icons/icon-utilities.tsx
  src/plugins/simulator/simulations/potentiometer-servo/potentiometer-servo.tsx
Labels: run regression, rete-v2, rete-v2-feature

#2265 187355848 shared program on rete v2
  cypress/e2e/functional/tile_tests/simulator_tile_spec.js
  src/models/shared/shared-program-data-registration.ts
  src/plugins/dataflow/assets/icons/sensor/emg.svg
  src/plugins/dataflow/components/dataflow-program.tsx
  src/plugins/dataflow/model/dataflow-content.ts
  src/plugins/dataflow/model/utilities/node.ts
  src/plugins/dataflow/nodes/rete-manager.tsx
  src/plugins/dataflow/nodes/utilities/shared-program-data-utilities.ts
  src/plugins/shared-assets/icons/dataflow/generator/noise.svg
  src/plugins/shared-assets/icons/dataflow/generator/sine.svg
  src/plugins/shared-assets/icons/dataflow/generator/square.svg
  src/plugins/shared-assets/icons/dataflow/generator/triangle.svg
  src/plugins/shared-assets/icons/dataflow/logic/and.svg
  src/plugins/shared-assets/icons/dataflow/logic/equal.svg
  src/plugins/shared-assets/icons/dataflow/logic/greater-than-or-equal-to.svg
  src/plugins/shared-assets/icons/dataflow/logic/greater-than.svg
  src/plugins/shared-assets/icons/dataflow/logic/less-than-or-equal-to.svg
  src/plugins/shared-assets/icons/dataflow/logic/less-than.svg
  src/plugins/shared-assets/icons/dataflow/logic/nand.svg
  src/plugins/shared-assets/icons/dataflow/logic/not-equal.svg
  src/plugins/shared-assets/icons/dataflow/logic/or.svg
  src/plugins/shared-assets/icons/dataflow/logic/xor.svg
  src/plugins/shared-assets/icons/dataflow/math/add.svg
  src/plugins/shared-assets/icons/dataflow/math/divide.svg
  src/plugins/shared-assets/icons/dataflow/math/multiply.svg
  src/plugins/shared-assets/icons/dataflow/math/subtract.svg
  src/plugins/shared-assets/icons/dataflow/sensor/co2.svg
  src/plugins/shared-assets/icons/dataflow/sensor/sensor-emg-icon.svg
  src/plugins/shared-assets/icons/dataflow/transform/absolute-value.svg
  src/plugins/shared-assets/icons/dataflow/transform/negation.svg
  src/plugins/shared-assets/icons/dataflow/transform/not.svg
  src/plugins/shared-assets/icons/icon-utilities.tsx
  src/plugins/shared-program-data/shared-program-data.ts
  src/plugins/simulator/components/simulator-tile.tsx
  src/plugins/simulator/model/simulator-content.ts
  src/plugins/simulator/simulations/potentiometer-servo/assets/assembly-expanded.png
  src/plugins/simulator/simulations/potentiometer-servo/assets/input-wire-curved.svg
  src/plugins/simulator/simulations/potentiometer-servo/assets/stopwatch.png
  src/plugins/simulator/simulations/potentiometer-servo/assets/stopwatch.svg
  src/plugins/simulator/simulations/potentiometer-servo/chip-sim-utils.tsx
  src/plugins/simulator/simulations/potentiometer-servo/potentiometer-servo.scss
  src/plugins/simulator/simulations/potentiometer-servo/potentiometer-servo.tsx
  src/plugins/simulator/simulations/simulation-types.tsx
  src/public/demo/docs/chipsimsetup.json
  src/register-tile-types.ts
Labels: run regression, rete-v2, rete-v2-feature

#2280 reload the zoom and translation of the program
  src/plugins/dataflow/components/dataflow-program.tsx
  src/plugins/dataflow/nodes/rete-manager.tsx
Labels: run regression
